### PR TITLE
start from original develop and add a date change to troubleshoot bui…

### PR DESCRIPTION
**Pull request by apger**
…ld process.  If this fails, it not a content issue

### CODE REVIEW

**Comment by miskoSplunk** [comment]
Change of code seems fine, let's wait for testing to get successful - I'm ok to merge this.

**Comment by miskoSplunk** [comment]
@apger it seems that CI does not see this PR's branch:
Cloning into 'security-content'...
warning: redirecting to https://github.com/splunk/security-content.git/
fatal: Remote branch pull/1497 not found in upstream origin

Would you know why that is the case - how did you commit the merge request?

**Comment by P4T12ICK** [comment]
There is a small bug in the new detection testing. I will fix it.

**Review by P4T12ICK — APPROVED** [review]
Looks good to me

**Pull request merged**
