### PR TITLE
AD_Discovery_TR-789_3

### PR DESCRIPTION
**Pull request by MHaggis**
## New Analytics

- get_domaintrust_with_powershell_script_block (Passed)
- get_domaintrust_with_powershell (Passed)
- Get-ForestTrust with PowerShell (Passed)
- Get-ForestTrust with PowerShell Script Block (Passed)

## Updated Analytics
- PowerShell Domain Enumeration (Passed)
-  Fileless Script Contains Base64 Encoded Content (Passed)
- Unloading AMSI via Reflection (Passed)

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Copy of ShadowCopy with Script Block Logging :white_check_mark:
- diskUsage: 163840
- runDuration: 1.026s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

PowerShell Domain Enumeration :white_check_mark:
- diskUsage: 163840
- runDuration: 1.133s
- scanCount: 47

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Get-ForestTrust with PowerShell Script Block :x:
- diskUsage: 155648
- runDuration: 1.327s
- scanCount: 13

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Get-DomainTrust with PowerShell Script Block :x:
- diskUsage: 139264
- runDuration: 0.003s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Get-ForestTrust with PowerShell :x:
- diskUsage: 573440
- runDuration: 1.839s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Get-DomainTrust with PowerShell :x:
- diskUsage: 565248
- runDuration: 1.832s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Get-DomainTrust with PowerShell Script Block :x:
- diskUsage: 139264
- runDuration: 0.003s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Get-ForestTrust with PowerShell Script Block :white_check_mark:
- diskUsage: 159744
- runDuration: 0.999s
- scanCount: 13

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Get-DomainTrust with PowerShell Script Block :x:
- diskUsage: 139264
- runDuration: 0.002s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Get-DomainTrust with PowerShell Script Block :x:
- diskUsage: 139264
- runDuration: 0.003s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Get-DomainTrust with PowerShell Script Block :x:
- diskUsage: 139264
- runDuration: 0.004s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Get-DomainTrust with PowerShell Script Block :x:
- diskUsage: 139264
- runDuration: 0.003s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Get-DomainTrust with PowerShell Script Block :x:
- diskUsage: 139264
- runDuration: 0.006s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Get-ForestTrust with PowerShell Script Block :white_check_mark:
- diskUsage: 159744
- runDuration: 0.9400000000000001s
- scanCount: 16

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Get-ForestTrust with PowerShell Script Block :white_check_mark:
- diskUsage: 159744
- runDuration: 0.987s
- scanCount: 16

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Get-DomainTrust with PowerShell Script Block :white_check_mark:
- diskUsage: 159744
- runDuration: 1.09s
- scanCount: 16

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Get-ForestTrust with PowerShell :white_check_mark:
- diskUsage: 585728
- runDuration: 2.332s
- scanCount: 4

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Get-DomainTrust with PowerShell :white_check_mark:
- diskUsage: 577536
- runDuration: 2.236s
- scanCount: 4

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

PowerShell Domain Enumeration :white_check_mark:
- diskUsage: 163840
- runDuration: 1.298s
- scanCount: 47

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
