### PR TITLE
FIN7

### PR DESCRIPTION
**Pull request by tccontre**
## FIN7 Detections

- Jscript Execution Using Cscript App (passed)
- Office Application Drop Executable (passed)
- XSL Script Execution With WMIC (passed)
- Non Chrome Process Accessing Chrome Default Dir (passed)
- Non Firefox Process Access Firefox Profile Dir (passed)
- Check Elevated CMD using whoami (passed)
- Cmdline Tool Not Executed In CMD Shell (passed)
- MS Scripting Process Loading WMI Module (passed)
- MS Scripting Process Loading ldap Module (passed)

## Analytic Story
fin7.yml

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

XSL Script Execution With WMIC :white_check_mark:
- diskUsage: 593920
- runDuration: 2.85s
- scanCount: 4

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Office Application Drop Executable :white_check_mark:
- diskUsage: 180224
- runDuration: 1.283s
- scanCount: 195

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Jscript Execution Using Cscript App :white_check_mark:
- diskUsage: 507904
- runDuration: 17.709s
- scanCount: 27859

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Non Firefox Process Access Firefox Profile Dir :white_check_mark:
- diskUsage: 200704
- runDuration: 1.499s
- scanCount: 121

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Non Chrome Process Accessing Chrome Default Dir :white_check_mark:
- diskUsage: 200704
- runDuration: 1.1360000000000001s
- scanCount: 41

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Office Application Drop Executable :white_check_mark:
- diskUsage: 1015808
- runDuration: 29.092000000000002s
- scanCount: 27859

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Check Elevated CMD using whoami :white_check_mark:
- diskUsage: 593920
- runDuration: 2.236s
- scanCount: 6

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Cmdline Tool Not Executed In CMD Shell :white_check_mark:
- diskUsage: 524288
- runDuration: 6.23s
- scanCount: 8131

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

MS Scripting Process Loading WMI Module :x:
- diskUsage: 184320
- runDuration: 1.057s
- scanCount: 99

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

MS Scripting Process Loading Ldap Module :x:
- diskUsage: 180224
- runDuration: 1.2670000000000001s
- scanCount: 100

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

MS Scripting Process Loading WMI Module :x:
- diskUsage: 184320
- runDuration: 1.577s
- scanCount: 98

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

MS Scripting Process Loading Ldap Module :x:
- diskUsage: 180224
- runDuration: 1.199s
- scanCount: 98

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

MS Scripting Process Loading Ldap Module :x:
- diskUsage: 180224
- runDuration: 1.539s
- scanCount: 98

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

MS Scripting Process Loading Ldap Module :x:
- diskUsage: 180224
- runDuration: 1.887s
- scanCount: 99

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

MS Scripting Process Loading Ldap Module :x:
- diskUsage: 180224
- runDuration: 0.981s
- scanCount: 99

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

MS Scripting Process Loading Ldap Module :x:
- diskUsage: 180224
- runDuration: 1.288s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

MS Scripting Process Loading WMI Module :x:
- diskUsage: 184320
- runDuration: 1.057s
- scanCount: 6

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

MS Scripting Process Loading WMI Module :x:
- diskUsage: 184320
- runDuration: 1.6500000000000001s
- scanCount: 6

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

MS Scripting Process Loading Ldap Module :x:
- diskUsage: 180224
- runDuration: 1.7810000000000001s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

MS Scripting Process Loading WMI Module :white_check_mark:
- diskUsage: 184320
- runDuration: 1.252s
- scanCount: 99

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

MS Scripting Process Loading Ldap Module :white_check_mark:
- diskUsage: 184320
- runDuration: 2.423s
- scanCount: 98

**Review by patel-bhavin — APPROVED** [review]

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
