### PR TITLE
Nterl0k T1036.002 - To the Right, To the Left, now slide.

### PR DESCRIPTION
**Pull request by nterl0k**
Pending approval of attack data in https://github.com/splunk/attack_data/pull/796

### Details

Detections for right to left override characters in file_name and process fields. A novel attacker technique to hide malicious files.

### Checklist

- [ ] Validate name matches `<platform>_<mitre att&ck technique>_<short description>` nomenclature
- [ ] [CI/CD](https://github.com/splunk/security_content/actions) jobs passed ✔️ 
- [ ] Validated SPL logic.
- [ ] Validated tags, description, and how to implement.
- [ ] Verified references match analytic.

### CODE REVIEW

**Comment by nterl0k** [comment]
Updated associated detections to align with 4.x schema

**Comment by patel-bhavin** [comment]
Thank you for updating to 4.X! i have merged your attack data and testing the two detections here : 
https://github.com/splunk/security_content/pull/2651/files

**Comment by patel-bhavin** [comment]
Hello @nterl0k : Apologies for the delay! I am getting a detection testing error on this search : `detections/endpoint/detect_rtlo_in_file_name.yml` in the duplicate PR, seems like there is an error with the dataset! Can you please check if the dataset is correct? if we are unable to get the correct dataset, we can ship this as experimental detection. 


image

**Comment by nterl0k** [comment]
@patel-bhavin  Interestingly enough my local copy of the dataset shows the RTLO char (UTF-8 encoding), however the data I uploaded to github seems to be clobbered with ANSI encoding.

Local file (UTF-8)
image

Github dataset (ANSI)
image


Is there some way to have Github treat the dataset as UTF8 when I upload (may be a mistake on my part) ?

**Comment by patel-bhavin** [comment]
@nterl0k : we looked into this issue and it seems like the Github UI is showing as ANSI but the indexed file is correct. I was able to  make a minor change to the quotes in the search and it worked locally. Thank you very much an awesome PR! Learnt lots about RTLO while testing this one. 

Closing this PR and merging : https://github.com/splunk/security_content/pull/2651/files where i made the changes 🙇‍♂️

**Comment by nterl0k** [comment]
Well bugger, I double quoted the SPL instead of a single quote.

My bad, thanks for cleaning up my mess!

Glad it's all good now.

**Pull request closed without merging**
