### PR TITLE
Tomorrow Never Haags

### PR DESCRIPTION
**Pull request by MHaggis**
## New Analytics

- Malicious InProcServer32 Modification
- Process Writing DynamicWrapperX
- Winhlp32 Spawning a Process

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Malicious InProcServer32 Modification :white_check_mark:
- diskUsage: 901120
- runDuration: 10.394s
- scanCount: 13937

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Winhlp32 Spawning a Process :white_check_mark:
- diskUsage: 606208
- runDuration: 9.301s
- scanCount: 13938

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Process Writing DynamicWrapperX :white_check_mark:
- diskUsage: 987136
- runDuration: 16.913s
- scanCount: 13938

**Review by tccontre — DISMISSED** [review]
LGTM

**Review by tccontre — APPROVED** [review]

**Pull request merged**
