### PR TITLE
O365 Bypass MFA via Trusted IP

### PR DESCRIPTION
**Pull request by patel-bhavin**
added detection and test file
added data to attack_data_repo
search tested using automated testing service
image

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

O365 Bypass MFA via Trusted IP :x:
- diskUsage: 147456
- runDuration: 0.524s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

O365 Bypass MFA via Trusted IP :x:
- diskUsage: 147456
- runDuration: 0.521s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

O365 Bypass MFA via Trusted IP :white_check_mark:
- diskUsage: 151552
- runDuration: 0.585s
- scanCount: 32

**Review by P4T12ICK — APPROVED** [review]
Looks good to me. Great work.

**Comment by ionsor** [comment]
The detection file doesn't match the test data anymore. The detection is for "Signature" field, when in test data the field is called "Operation". I am not sure which file needs to be corrected

**Pull request merged**
