### PR TITLE
Double The Bacon and Haags

### PR DESCRIPTION
**Pull request by MHaggis**
## New Analytics
- CMD Echo Pipe - Escalation (Passed)
- Detect AzureHound File Modifications (Passed)
- Detect SharpHound Command-Line Arguments (Passed)
- Detect SharpHound File Modifications (Passed)
- Detect SharpHound Usage (Passed)
- Detect Renamed Psexec (Passed)
- Detect Renamed 7-Zip (Passed)
- Detect Renamed WinRAR (Passed)
- Detect AzureHound Command-Line Arguments (Passed)

## Updated Analytic Story
- Windows Discovery Techniques

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

CMD Echo Pipe - Escalation :white_check_mark:
- diskUsage: 421888
- runDuration: 54.692s
- scanCount: 104036

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect AzureHound File Modifications :white_check_mark:
- diskUsage: 446464
- runDuration: 2.129s
- scanCount: 18

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect SharpHound File Modifications :white_check_mark:
- diskUsage: 434176
- runDuration: 2.236s
- scanCount: 73

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect SharpHound Usage :white_check_mark:
- diskUsage: 258048
- runDuration: 0.869s
- scanCount: 94

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect SharpHound Command-Line Arguments :white_check_mark:
- diskUsage: 512000
- runDuration: 1.559s
- scanCount: 9

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Renamed PSExec :x:
- diskUsage: 253952
- runDuration: 0.8310000000000001s
- scanCount: 4

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Renamed PSExec :white_check_mark:
- diskUsage: 258048
- runDuration: 0.892s
- scanCount: 7

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Renamed 7-Zip :white_check_mark:
- diskUsage: 258048
- runDuration: 0.916s
- scanCount: 126

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Renamed WinRAR :white_check_mark:
- diskUsage: 258048
- runDuration: 1.2550000000000001s
- scanCount: 261

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect AzureHound Command-Line Arguments :white_check_mark:
- diskUsage: 503808
- runDuration: 1.5230000000000001s
- scanCount: 28

**Review by patel-bhavin — APPROVED** [review]

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
