### PR TITLE
WIP - rel1 02-2020

### PR DESCRIPTION
**Pull request by MHaggis**
Broke out ntdsutil.exe from creation_of_shadow_copy to allow for better filtering and specific monitoring/alerting.

Analytic Story
- Suspicious Regsvr32 Activity
- Suspicious Rundll32 Activity

Analytics
- Detect Regsvr32 Application Control Bypass (Passed)
- Suspicious regsvr32 register suspicious path (Passed)
- ntdsutil_export_ntds (Passed)
- Dump lsass via procdump (Passed)
- Dump lsass via procdump rename (Passed)
- Creation of lsass dump with taskmgr (Passed)
- Suspicious rundll32 rename (Passed)
- Detect Rundll32 Application Control Bypass - advpack & ieadvpack (Passed)
- Detect Rundll32 Application Control Bypass - syssetup (Passed)
- Detect Rundll32 Application Control Bypass - setupapi (Passed)  
- Suspicious Rundll32 StartW (Passed)
- Suspicious Rundll32 DllRegisterServer (Passed)
- Suspicious Rundll32 with no command line arguments (Passed)

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

NTdsutil to export ntds dit from Directory Services :white_check_mark:
- diskUsage: 356352
- runDuration: 5.223s
- scanCount: 6754

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect regsvr32 Application Control Bypass :white_check_mark:
- diskUsage: 372736
- runDuration: 3.186s
- scanCount: 3058

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect regsvr32 Registering DLLs from non-standard paths :white_check_mark:
- diskUsage: 393216
- runDuration: 3.275s
- scanCount: 3058

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect renamed regsvr32 execution :x:
- diskUsage: 245760
- runDuration: 0.895s
- scanCount: 12

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect renamed regsvr32 execution :x:
- diskUsage: 126976
- runDuration: 0.646s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect renamed regsvr32 execution :x:
- diskUsage: 262144
- runDuration: 0.812s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Dump LSASS via procdump :white_check_mark:
- diskUsage: 495616
- runDuration: 2.116s
- scanCount: 199

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Dump lsass via procdump rename :white_check_mark:
- diskUsage: 258048
- runDuration: 0.9460000000000001s
- scanCount: 36

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Creation of lsass dump with taskmgr :white_check_mark:
- diskUsage: 286720
- runDuration: 0.9440000000000001s
- scanCount: 24

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Rundll32 Application Control Bypass - advpack and ieadvpack :white_check_mark:
- diskUsage: 270336
- runDuration: 0.976s
- scanCount: 64

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Renamed rundll32.exe Rename :white_check_mark:
- diskUsage: 143360
- runDuration: 0.838s
- scanCount: 64

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Rundll32 Application Control Bypass - syssetup :white_check_mark:
- diskUsage: 393216
- runDuration: 7.343s
- scanCount: 9914

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Rundll32 Application Control Bypass - setupapi :white_check_mark:
- diskUsage: 393216
- runDuration: 7.304s
- scanCount: 9914

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious Rundll32 startw :white_check_mark:
- diskUsage: 397312
- runDuration: 9.200000000000001s
- scanCount: 13107

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious Rundll32 with no Command Line Arguments :white_check_mark:
- diskUsage: 286720
- runDuration: 8.298s
- scanCount: 13107

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious Rundll32 dllregisterserver :white_check_mark:
- diskUsage: 397312
- runDuration: 9.259s
- scanCount: 13107

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect renamed regsvr32 execution :x:
- diskUsage: 126976
- runDuration: 0.672s
- scanCount: 0

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
