### PR TITLE
minor_update_saa_urlscan_playbook

### PR DESCRIPTION
**Pull request by tccontre**
# Pull Request Type

##### Please check all that apply:
- [x] New playbook
- [ ] Bugfix
- [ ] Feature add
- [ ] Code style update (formatting, renaming)
- [ ] Documentation
- [ ] Other (please describe): 

# Release Notes
Replace the following list with release notes that describe the high level components of the PR:
- Feature - Added new playbook for reputation checks
- Bug - Fixed python logic for a custom code block
- etc. etc.

# Playbook quality checklist
Please check if your PR fulfills the following requirements.

### Requirements for Settings

- [x] Playbook name is A-Z in Title case with underscores between words. (e.g. MS_Graph_Search_and_Purge)
- [ ] Category in Title case with spaces between words (e.g. Identifier Reputation Analysis)
- [x] Description is free of grammatical errors and describe what the playbook does.
- [x] Notes list any setup required on the third-party API as well as intended areas for customization.
- [ ] Label is set to '\*'
    
### Requirements for all playbooks

- [x] Playbook block count not greater than 15 (not including Start and End blocks).
- [x] No more than 3 branching paths.
- [x] If referencing a custom list, Notes document what the expected values are in that custom list.

### Requirements for all playbook blocks

- [x] All blocks have a custom name no more than 4 words, all lowercase, and separated by space (e.g. close workbook task)
- [x] All blocks that support a Notes Tooltip have it filled out. Must be grammatically correct and describes the intended purpose of that block.
- [x] Where custom code is used, block notes indicate presence of custom code (e.g. "This block uses custom code")
- [x] No block is disabled by custom code
- [x] Custom code is documented with notes

##### Action

- [x] Use apps available on Splunkbase
- [x] Use asset names that are the app name, all lowercase separated by underscores (e.g. Azure AD Graph becomes azure_ad_graph)

##### Utility 

- [x] Block is using community version

##### Playbook

- [x] Block is using local version

##### Input playbooks
- [x] Start blocks use ocsf variable names and a minimum of one data type per variable name (e.g. device (type: host name))
- [x] Has at least one category tag (e.g. reputation)
- [x] Playbook has a tag for each vendor app used

# Other considerations (PR type specific)
- [x] If new playbook, there is a screenshot ending in .png with the same name as the playbook .json
- [ ] Playbook major minor version matches repo (e.g. 5.5 != 6.0)
- [x] PR contains both .py and .json

---
Thanks for contributing!

### CODE REVIEW

**Review by P4T12ICK — CHANGES_REQUESTED** [review]
- Custom Code Block build file output in SAA Dynamic Analysis Playbook has a debug statement not commented out
- One block in SAA is called filter 5, please give it a descriptive name and a description

**Comment by tccontre** [comment]
> * Custom Code Block build file output in SAA Dynamic Analysis Playbook has a debug statement not commented out
> * One block in SAA is called filter 5, please give it a descriptive name and a description

fixed. :)

**Comment by P4T12ICK** [comment]
Looks good to me

**Comment by kelby-shelton** [comment]
Issues with urlscan playbook:

1. There should be no format block where an error code has occurred.
2. There should be no normalized output where an error code has occurred.
3. Sandbox sub dictionary should be called "reputation" and not sandbox.
4. Format block for no error code is missing a second `%%` 
5. Observable output is missing the hostname of the url when the url is doesn't have a leading http or https. We should investigate how we can extract a domain for when a url doesn't have http or https.

**Comment by tccontre** [comment]
> Issues with urlscan playbook:
> 
> 1. There should be no format block where an error code has occurred.
> 2. There should be no normalized output where an error code has occurred.
> 3. Sandbox sub dictionary should be called "reputation" and not sandbox.
> 4. Format block for no error code is missing a second `%%`
> 5. Observable output is missing the hostname of the url when the url is doesn't have a leading http or https. We should investigate how we can extract a domain for when a url doesn't have http or https.

fixed

**Review by P4T12ICK — APPROVED** [review]

**Pull request merged**
