### PR TITLE
[TR-213] basic risk tagging check in validate_ssa.py

### PR DESCRIPTION
**Pull request by jzsplunk**
(WIP) add basic check for risk tagging in validate_ssa.py.  There is an error being thrown on my local without the tag checking logic enabled and after updating to the latest jdk. 

`(venv) ➜  security-content git:(TR-213-ssa_risk_tags) ✗ python3 bin/validate_ssa.py tests/endpoint/attempted_credential_dump_from_registry_via_reg_exe___ssa.test.yml
2020-10-28 02:57:07 - INFO - Testing Attempted Credential Dump From Registry via Reg exe - SSA Unit test
2020-10-28 02:57:08 - INFO - Humvee test Attempted Credential Dump From Registry via Reg exe
2020-10-28 02:57:16 - INFO - Attempted Credential Dump From Registry via Reg exe executed without issues
2020-10-28 02:57:16 - INFO - Passed tests
tests/endpoint/attempted_credential_dump_from_registry_via_reg_exe___ssa.test.yml
2020-10-28 02:57:16 - INFO - Failed tests`

### CODE REVIEW

**Comment by ghoto** [comment]
Are we moving this logic to validate.py?

**Comment by jzsplunk** [comment]
@ghoto yes I think we will move this logic I will confirm before I close this.

**Comment by patel-bhavin** [comment]
@jzsplunk : This looks incorrect, we need to add a logic that checks `risk_severity = <enum values>` when type of detection is SSA. I believe this logic can be in both `validate.py`and `validate_ssa.py`

**Comment by ghoto** [comment]
We added validation to ssa in `bin/ssa_validate.py` new script. Please submit any changes in that file.

**Pull request closed without merging**
