### PR TITLE
linux_persist_priv_batch_3

### PR DESCRIPTION
**Pull request by tccontre**
### change ownership, kernel driver loading, hijack library, sudoers modification

- linux_change_file_owner_to_root.yml (passed)
- linux_file_created_in_kernel_driver_directory.yml (passed)
- linux_insert_kernel_module_using_insmod_utility.yml (passed)
- linux_install_kernel_module_using_modprobe_utility.yml (passed)
- linux_preload_hijack_library_calls.yml 
- linux_sudoers_tmp_file_creation.yml (passed)
- linux_visudo_utility_execution.yml (passed)

### Docker Testing (All detection passed - success.csv)
Screenshot 2022-01-05 at 13 48 13

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Preload Hijack Library Calls :x:
- diskUsage: 507904
- runDuration: 3.181s
- scanCount: 2805

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Change File Owner To Root :white_check_mark:
- diskUsage: 602112
- runDuration: 5.115s
- scanCount: 3622

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Visudo Utility Execution :white_check_mark:
- diskUsage: 434176
- runDuration: 16.240000000000002s
- scanCount: 29556

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Sudoers Tmp File Creation :white_check_mark:
- diskUsage: 446464
- runDuration: 5.58s
- scanCount: 6489

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Install Kernel Module Using Modprobe Utility :white_check_mark:
- diskUsage: 507904
- runDuration: 2.825s
- scanCount: 1825

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux File Created In Kernel Driver Directory :white_check_mark:
- diskUsage: 430080
- runDuration: 11.021s
- scanCount: 15252

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Change File Owner To Root :white_check_mark:
- diskUsage: 421888
- runDuration: 3.509s
- scanCount: 3619

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Preload Hijack Library Calls :x:
- diskUsage: 589824
- runDuration: 3.487s
- scanCount: 2807

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
