### PR TITLE
AWS Privilege Escalation

### PR DESCRIPTION
**Pull request by patel-bhavin**
## New analytic story
- AWS IAM Privilege Escalation

## New Detections
- AWS Create Policy Version to allow all resources(passed)
- AWS SetDefaultPolicyVersion(passed)
- AWS CreateAccessKey(passed)
- AWS CreateLoginProfile(passed)
- AWS UpdateLoginProfile(passed)

## Other Updates
- Added  product and risk tag to ALL Cloudtraill searches  that have been tested

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

AWS Create Policy Version to allow all resources :x:
- diskUsage: 147456
- runDuration: 0.755s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

AWS Create Policy Version to allow all resources :x:
- diskUsage: 143360
- runDuration: 0.289s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

AWS Create Policy Version to allow all resources :white_check_mark:
- diskUsage: 155648
- runDuration: 0.753s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

AWS Create Policy Version to allow all resources :white_check_mark:
- diskUsage: 155648
- runDuration: 0.78s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

AWS Create Policy Version to allow all resources :white_check_mark:
- diskUsage: 155648
- runDuration: 0.708s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

AWS Create Policy Version to allow all resources :white_check_mark:
- diskUsage: 155648
- runDuration: 0.745s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

AWS SetDefaultPolicyVersion :white_check_mark:
- diskUsage: 135168
- runDuration: 0.714s
- scanCount: 4

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

AWS CreateAccessKey :white_check_mark:
- diskUsage: 139264
- runDuration: 0.75s
- scanCount: 23

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

AWS UpdateLoginProfile :white_check_mark:
- diskUsage: 139264
- runDuration: 0.767s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

AWS CreateLoginProfile :white_check_mark:
- diskUsage: 196608
- runDuration: 1.038s
- scanCount: 3

**Review by MHaggis — APPROVED** [review]

**Pull request merged**
