### PR TITLE
Lateral Movement Content Update #1

### PR DESCRIPTION
**Pull request by mvelazc0**
## New Detections

- Windows Service Creation on Remote Endpoint
- Windows Service Initiation on Remote Endpoint
- Scheduled Task Initiation on Remote Endpoint
- Scheduled Task Creation on Remote Endpoint using At
- Remote Process Instantiation via WinRM and Winrs

## Updated Detections
 - Schtasks scheduling job on remote system
 -  Remote Process Instantiation via WMI

All detections have passed testing.

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Remote Process Instantiation via WinRM and Winrs :x:
- diskUsage: 487424
- runDuration: 1.869s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Scheduled Task Initiation on Remote Endpoint :white_check_mark:
- diskUsage: 602112
- runDuration: 4.292s
- scanCount: 4045

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Scheduled Task Creation on Remote Endpoint using At :white_check_mark:
- diskUsage: 499712
- runDuration: 3.791s
- scanCount: 3537

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Remote Process Instantiation via WinRM and Winrs :white_check_mark:
- diskUsage: 602112
- runDuration: 4.104s
- scanCount: 3726

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows Service Creation on Remote Endpoint :white_check_mark:
- diskUsage: 438272
- runDuration: 3.923s
- scanCount: 3526

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows Service Initiation on Remote Endpoint :white_check_mark:
- diskUsage: 430080
- runDuration: 3.793s
- scanCount: 3526

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Remote Process Instantiation via WMI :white_check_mark:
- diskUsage: 614400
- runDuration: 5.655s
- scanCount: 6575

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Schtasks scheduling job on remote system :white_check_mark:
- diskUsage: 520192
- runDuration: 5.2620000000000005s
- scanCount: 6286

**Review by MHaggis — APPROVED** [review]

**Pull request merged**
