### PR TITLE
The Prodigal Haag Returns

### PR DESCRIPTION
**Pull request by MHaggis**
## New Analytics
- WMIC XSL Execution via URL (Passed)
- Windows InstallUtil Remote Network Connection (Passed)
- Windows InstallUtil URL in Command Line (Passed)
- Windows InstallUtil Credential Theft (Passed)
- Windows InstallUtil Uninstall Option (Passed)
- Windows InstallUtil Uninstall Option with Network (Passed)
- Windows DiskCryptor Usage (Passed)
## New Analytic Story
- Signed Binary Proxy Execution InstallUtil

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

WMIC XSL Execution via URL :x:
- diskUsage: 573440
- runDuration: 1.947s
- scanCount: 4

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

WMIC XSL Execution via URL :white_check_mark:
- diskUsage: 610304
- runDuration: 7.347s
- scanCount: 7874

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows InstallUtil Credential Theft :x:
- diskUsage: 311296
- runDuration: 1.147s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows InstallUtil Remote Network Connection :x:
- diskUsage: 679936
- runDuration: 2.053s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows InstallUtil Uninstall Option with Network :x:
- diskUsage: 614400
- runDuration: 2.324s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows InstallUtil Uninstall Option :x:
- diskUsage: 479232
- runDuration: 1.976s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows InstallUtil URL in Command Line :x:
- diskUsage: 479232
- runDuration: 2.007s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows InstallUtil Credential Theft :x:
- diskUsage: 339968
- runDuration: 1.127s
- scanCount: 4

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows InstallUtil Uninstall Option with Network :x:
- diskUsage: 757760
- runDuration: 3.396s
- scanCount: 1611

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows InstallUtil Remote Network Connection :x:
- diskUsage: 757760
- runDuration: 3.141s
- scanCount: 1611

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows InstallUtil Uninstall Option :white_check_mark:
- diskUsage: 507904
- runDuration: 2.868s
- scanCount: 1611

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows InstallUtil Credential Theft :x:
- diskUsage: 339968
- runDuration: 1.349s
- scanCount: 4

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows InstallUtil Uninstall Option with Network :x:
- diskUsage: 757760
- runDuration: 3.999s
- scanCount: 1611

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows InstallUtil URL in Command Line :white_check_mark:
- diskUsage: 401408
- runDuration: 2.954s
- scanCount: 1609

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows InstallUtil Uninstall Option with Network :white_check_mark:
- diskUsage: 753664
- runDuration: 3.852s
- scanCount: 1628

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows InstallUtil URL in Command Line :white_check_mark:
- diskUsage: 499712
- runDuration: 2.746s
- scanCount: 1628

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows InstallUtil Credential Theft :white_check_mark:
- diskUsage: 335872
- runDuration: 1.147s
- scanCount: 4

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows InstallUtil Remote Network Connection :white_check_mark:
- diskUsage: 704512
- runDuration: 3.567s
- scanCount: 1628

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Plink Remote Forwarding :x:
- diskUsage: 634880
- runDuration: 2.846s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows Enable DefaultAccount :x:
- diskUsage: 503808
- runDuration: 2.335s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows DiskCryptor Usage :x:
- diskUsage: 401408
- runDuration: 1.958s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Plink Remote Forwarding :x:
- diskUsage: 557056
- runDuration: 2.97s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows DiskCryptor Usage :white_check_mark:
- diskUsage: 499712
- runDuration: 1.929s
- scanCount: 87

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows DiskCryptor Usage :white_check_mark:
- diskUsage: 425984
- runDuration: 2.054s
- scanCount: 87

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Plink Remote Forwarding :x:
- diskUsage: 634880
- runDuration: 3.0420000000000003s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows DiskCryptor Usage :white_check_mark:
- diskUsage: 499712
- runDuration: 2.013s
- scanCount: 87

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Plink Remote Forwarding :x:
- diskUsage: 516096
- runDuration: 4.087s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows Enable DefaultAccount :x:
- diskUsage: 454656
- runDuration: 2.249s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows Enable DefaultAccount :x:
- diskUsage: 503808
- runDuration: 2.063s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows Enable DefaultAccount :x:
- diskUsage: 503808
- runDuration: 2.435s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Plink Remote Forwarding :x:
- diskUsage: 466944
- runDuration: 3.208s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows Enable DefaultAccount :x:
- diskUsage: 397312
- runDuration: 1.97s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Plink Remote Forwarding :x:
- diskUsage: 462848
- runDuration: 3.9010000000000002s
- scanCount: 1

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
