### PR TITLE
Sneaky Active Directory Persistence Tricks

### PR DESCRIPTION
**Pull request by mvelazc0**
## New Analytic Story

- Sneaky Active Directory Persistence Tricks 

## New Tested Detections

- Windows AD Same Domain SID History Addition
- Windows AD Cross Domain SID History Addition
- Windows AD Replication Request Initiated by User Account
- Windows AD Replication Request Initiated from Unsanctioned Location
- Windows AD Domain Replication ACL Addition
- Windows AD DSRM Account Changes
- Windows AD DSRM Password Reset
- Windows AD Short Lived Domain Controller SPN Attribute
- Windows AD Short Lived Server Object
- Windows AD SID History Attribute Modified
- Windows AD AdminSDHolder ACL Modified
- Windows AD ServicePrincipalName Added To Domain Account
- Windows AD Short Lived Domain Account ServicePrincipalName

## New Experimental Detections
- Windows AD Rogue Domain Controller Network Activity
- Windows AD Account SID History Addition
- Windows AD Replication Service Traffic

_What does this PR have in it? Screenshots are worth 1000 words 😄_

### Checklist

- [ ] Validate name matches `<platform>_<mitre att&ck technique>_<short description>` nomenclature
- [ ] [CI/CD](https://github.com/splunk/security_content/actions) jobs passed ✔️ 
- [ ] Validated SPL logic.
- [ ] Validated tags, description, and how to implement.
- [ ] Verified references match analytic.

### CODE REVIEW

**Comment by nterl0k** [comment]
I have a similar detection to "Rogue DC Network Activity", but it's more geared towards NGFW/app aware firewalls (Palo Alto, Cisco, etc), so it may provide more coverage.

Uses the following code:
Description
```
This search looks for evidence of Active Directory replication traffic [MS-DRSR] from unexpected sources. This traffic is often seen exclusively between Domain Controllers for AD database replication. Any detections from non-domain controller source to a domain controller may indicate the usage of "DCSync" or "DCShadow" credential dumping techniques. 

Alter traffic "app" as appropriate for your application aware/NGFW technology.

https://adsecurity.org/?p=1729
https://attack.mitre.org/techniques/T1003/006/
https://attack.mitre.org/techniques/T1207/
```

Code
```
| tstats `security_content_summariesonly` count values(All_Traffic.transport) as transport values(All_Traffic.user) as user values(All_Traffic.src_category) as src_category values(All_Traffic.dest_category) as dest_category min(_time) as firstTime max(_time) as lastTime from datamodel=Network_Traffic where All_Traffic.app IN ("ms-dc-replication","*drsr*","ad drs") by All_Traffic.src All_Traffic.dest All_Traffic.app
| `security_content_ctime(firstTime)` 
| `security_content_ctime(lastTime)` 
| `drop_dm_object_name("All_Traffic")`
| `active_directory_replication_traffic_from_unknown_source_filter`
```
The filtering macro is setup up similar with "search NOT (src_category=domain_controller dest_category=domain_controller)"

Also have some detections developed for DCSync/DCShadow I was planning up do a pull request for, but i'm happy to contribute to this branch

**Comment by dluxtron** [comment]
> I have a similar detection to "Rogue DC Network Activity", but it's more geared towards NGFW/app aware firewalls (Palo Alto, Cisco, etc), so it may provide more coverage.
> 
> Uses the following code: Description
> 
> ```
> This search looks for evidence of Active Directory replication traffic [MS-DRSR] from unexpected sources. This traffic is often seen exclusively between Domain Controllers for AD database replication. Any detections from non-domain controller source to a domain controller may indicate the usage of "DCSync" or "DCShadow" credential dumping techniques. 
> 
> Alter traffic "app" as appropriate for your application aware/NGFW technology.
> 
> https://adsecurity.org/?p=1729
> https://attack.mitre.org/techniques/T1003/006/
> https://attack.mitre.org/techniques/T1207/
> ```
> 
> Code
> 
> ```
> | tstats `security_content_summariesonly` count values(All_Traffic.transport) as transport values(All_Traffic.user) as user values(All_Traffic.src_category) as src_category values(All_Traffic.dest_category) as dest_category min(_time) as firstTime max(_time) as lastTime from datamodel=Network_Traffic where All_Traffic.app IN ("ms-dc-replication","*drsr*","ad drs") by All_Traffic.src All_Traffic.dest All_Traffic.app
> | `security_content_ctime(firstTime)` 
> | `security_content_ctime(lastTime)` 
> | `drop_dm_object_name("All_Traffic")`
> | `active_directory_replication_traffic_from_unknown_source_filter`
> ```
> 
> The filtering macro is setup up similar with "search NOT (src_category=domain_controller dest_category=domain_controller)"
> 
> Also have some detections developed for DCSync/DCShadow I was planning up do a pull request for, but i'm happy to contribute to this branch

Mate, this detection looks great! 

Very keen to see your DCSync/ Shadow detections too, do you use any detection logic different to the ones in this analytic story? 

DCSync
Windows AD Replication Request Initiated by User Account
Windows AD Replication Request Initiated from Unsanctioned Location

DCShadow
Windows AD Short Lived Domain Controller SPN Attribute
Windows AD Short Lived Server Object

**Comment by nterl0k** [comment]
> Mate, this detection looks great!
> 
> Very keen to see your DCSync/ Shadow detections too, do you use any detection logic different to the ones in this analytic story?
> 
> DCSync Windows AD Replication Request Initiated by User Account Windows AD Replication Request Initiated from Unsanctioned Location
> 
> DCShadow Windows AD Short Lived Domain Controller SPN Attribute Windows AD Short Lived Server Object

@dluxtron It looks like your DCSync detections are pretty close to mine, I'm also using 4662... The downside to 4662 is that it's pretty noisy in a production environment...so it's probably advisable to filter it at the forwarder post implementation.

Your DCShadow detection is novel, I hadn't considered using 5136 or 5137, since they're also fairly chatty when enabled. I'm using the computer account created/changed (4741/4742) events which also gets you SPN data. Looking for the same GC or GUID values.

Here's some links to the ones I was planning to submit, feel free to take inspiration/include. Just happy to contribute.
Story
- https://github.com/nterl0k/security_content/blob/nterl0k-ad-repl-attacks/stories/active_directory_replication_attacks.yml

Detections
- https://github.com/nterl0k/security_content/blob/nterl0k-ad-repl-attacks/detections/endpoint/detect_possible_dcshadow_attack.yml
- https://github.com/nterl0k/security_content/blob/nterl0k-ad-repl-attacks/detections/endpoint/detect_possible_dcsync_attack.yml
- https://github.com/nterl0k/security_content/blob/nterl0k-ad-repl-attacks/detections/network/detect_directory_replication_service_traffic.yml

**Comment by nterl0k** [comment]
@mvelazc0 @dluxtron 

Any thoughts on including my logic as an alternative for your DCShadow /Replication GUID detection?

During a recent red team event this detection was pretty helpful. 

https://github.com/nterl0k/security_content/blob/nterl0k-ad-repl-attacks/detections/endpoint/detect_possible_dcshadow_attack.yml

**Comment by mvelazc0** [comment]
Hi @nterl0k ! Sorry for the late reply, we are finalizing the touches on this PR before releasing. 

Do you have a dataset for this detection ? If not, we can generate one.

Can you jump on a zoom for 15 min to chat about this. Thanks

**Comment by nterl0k** [comment]
@mvelazc0 I believe the "Detect DC Promotion" analytic in this story set is pretty close to mine (looking at the DC/GUID detection in EventID 4742). I believe you could use the same dataset as a test for mine, but notionally they're probably close enough to call them the same (not sure if mine inspired youz detection or I just missed it originally)

https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1207/dc_promo/windows-security-xml.log

https://github.com/splunk/security_content/pull/2347/files#diff-0483a3391a8303f4eec023ce4c28379e2190d15b17d453c23c2fbd5ac49e4627

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
