### PR TITLE
AD_Discovery_TR-789_9

### PR DESCRIPTION
**Pull request by mvelazc0**
## New T1033 detections

* System User Discovery With Query
* System User Discovery With Whoami
* GetCurrent User with PowerShell Script Block
* GetCurrent User with PowerShell
* User Discovery With Env Vars PowerShell
* User Discovery With Env Vars PowerShell Script Block

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetCurrent User with PowerShell :x:
- diskUsage: 491520
- runDuration: 3.834s
- scanCount: 2786

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

System User Discovery With Query :white_check_mark:
- diskUsage: 487424
- runDuration: 3.301s
- scanCount: 2786

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetCurrent User with PowerShell Script Block :x:
- diskUsage: 155648
- runDuration: 1.0050000000000001s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

System User Discovery With Whoami :white_check_mark:
- diskUsage: 491520
- runDuration: 3.222s
- scanCount: 2786

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

User Discovery With Env Vars PowerShell Script Block :white_check_mark:
- diskUsage: 159744
- runDuration: 1.114s
- scanCount: 19

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

User Discovery With Env Vars PowerShell :white_check_mark:
- diskUsage: 368640
- runDuration: 1.965s
- scanCount: 4

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetCurrent User with PowerShell :white_check_mark:
- diskUsage: 495616
- runDuration: 3.461s
- scanCount: 2731

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetCurrent User with PowerShell Script Block :white_check_mark:
- diskUsage: 159744
- runDuration: 1.0190000000000001s
- scanCount: 2

**Review by MHaggis — APPROVED** [review]

**Pull request merged**
