### PR TITLE
virustotal_v3_dynamic_analysis_playbooks

### PR DESCRIPTION
**Pull request by tccontre**
# Pull Request Type

##### Please check all that apply:
- [x] New playbook
- [ ] Bugfix
- [ ] Feature add
- [ ] Code style update (formatting, renaming)
- [ ] Documentation
- [ ] Other (please describe): 

# Release Notes
Replace the following list with release notes that describe the high level components of the PR:
- [x] playbooks/VirusTotal_v3_Dynamic_Analysis.json
- [x] playbooks/VirusTotal_v3_Dynamic_Analysis.png
- [x]  playbooks/VirusTotal_v3_Dynamic_Analysis.py
- [x]  playbooks/VirusTotal_v3_Dynamic_Analysis.yml

# Playbook quality checklist
Please check if your PR fulfills the following requirements.

### Requirements for Settings

- [x] Playbook name is A-Z in Title case with underscores between words. (e.g. MS_Graph_Search_and_Purge)
- [ ] Category in Title case with spaces between words (e.g. Identifier Reputation Analysis)
- [x] Description is free of grammatical errors and describe what the playbook does.
- [x] Notes list any setup required on the third-party API as well as intended areas for customization.
- [ ] Label is set to '\*'
    
### Requirements for all playbooks

- [x] Playbook block count not greater than 15 (not including Start and End blocks).
- [x] No more than 3 branching paths.
- [x] If referencing a custom list, Notes document what the expected values are in that custom list.

### Requirements for all playbook blocks

- [x] All blocks have a custom name no more than 4 words, all lowercase, and separated by space (e.g. close workbook task)
- [x] All blocks that support a Notes Tooltip have it filled out. Must be grammatically correct and describes the intended purpose of that block.
- [x] Where custom code is used, block notes indicate presence of custom code (e.g. "This block uses custom code")
- [x] No block is disabled by custom code
- [x] Custom code is documented with notes

##### Action

- [x] Use apps available on Splunkbase
- [x] Use asset names that are the app name, all lowercase separated by underscores (e.g. Azure AD Graph becomes azure_ad_graph)

##### Utility 

- [x] Block is using community version

##### Playbook

- [x] Block is using local version

##### Input playbooks
- [x] Start blocks use ocsf variable names and a minimum of one data type per variable name (e.g. device (type: host name))
- [x] Has at least one category tag (e.g. reputation)
- [x] Playbook has a tag for each vendor app used

# Other considerations (PR type specific)
- [x] If new playbook, there is a screenshot ending in .png with the same name as the playbook .json
- [x] Playbook major minor version matches repo (e.g. 5.5 != 6.0)
- [x] PR contains both .py and .json

---
Thanks for contributing!

### CODE REVIEW

**Review by P4T12ICK — CHANGES_REQUESTED** [review]
- Rename reputation in observable to sandbox

**Comment by tccontre** [comment]
> * Rename reputation in observable to sandbox
status:
done: "reputation" dictionary in observables was renamed to "sandbox"

**Comment by P4T12ICK** [comment]
Looks good to me

**Comment by kelby-shelton** [comment]
1. Ran into bug with file detonation when there is a file that doesn't return all of the expected attributes. I recommend rewriting this section in build_file_output:
```
"attributes": {
                "type": file_data['attributes']['type_extension'],
                "name": file_data['attributes']['meaningful_name'],
                "size": file_data['attributes']['size'],
                "md5": file_data['attributes']['md5'],
                "sha1": file_data['attributes']['sha1'],
                "sha256": file_data['attributes']['sha256']
            }
```

to use .get calls e.g. `file_data['attributes'].get('type_extension')`

2. Forgot to delete extra variables in format_report_url and format_report_file:

Screenshot 2023-04-03 at 2 46 44 PM
Screenshot 2023-04-03 at 2 47 31 PM

**Review by P4T12ICK — APPROVED** [review]

**Comment by patel-bhavin** [comment]
Playbook was approved and tagged with 4.0.0

**Pull request merged**
