### PR TITLE
Tr 215 crypto story

### PR DESCRIPTION
**Pull request by jzsplunk**
(WIP) Do Not Merge

@P4T12ICK I pushed the latest changes from this branch to one of our test instances with the risk scoring index populated, but still not seeing a notable event anything missing you notice from the YAML?

### CODE REVIEW

**Comment by miskoSplunk** [comment]
To me these seem conceptually solid.
Don't know what are the SPL macros underneath to do a more detailed review.

**Comment by josehelps** [comment]
@jzsplunk where are we with this PR, it has been up for a while ready to merge yet?

**Comment by jzsplunk** [comment]
CC: Dorsey is helping with a blocker that is preventing us from closing
this.

**Comment by josehelps** [comment]
see comments on https://github.com/splunk/security_content/pull/1317 .. closing due to stale. Re-open when ready to merge.

**Pull request closed without merging**
