### PR TITLE
T1197 BITS Jobs

### PR DESCRIPTION
**Pull request by MHaggis**
## New Analytic Stories
- Bits Jobs
- Domain Trust Discovery

## New Detections
- BITSAdmin Download File (Passed)
- BITS Job Persistence (Passed)
- PowerShell Start-BitsTransfer (Passed)
- DSQuery Domain Discovery (Passed)

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

BITSAdmin Download File :white_check_mark:
- diskUsage: 397312
- runDuration: 3.136s
- scanCount: 2758

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

BITS Job Persistence :white_check_mark:
- diskUsage: 421888
- runDuration: 4.244s
- scanCount: 2758

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

PowerShell Start-BitsTransfer :white_check_mark:
- diskUsage: 495616
- runDuration: 1.485s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

DSQuery Domain Discovery :white_check_mark:
- diskUsage: 393216
- runDuration: 1.6260000000000001s
- scanCount: 263

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
