### PR TITLE
AD_Discovery_TR-789_6

### PR DESCRIPTION
**Pull request by mvelazc0**
## New T1069.002  Detections

* Domain Group Discovery With Net
* Domain Group Discovery With Dsquery
* Elevated Group Discovery With Net
* Domain Group Discovery With Wmic
* Elevated Group Discovery With Wmic
* Domain Group Discovery with Adsisearcher
* GetAdGroup with PowerShell Script Block
* GetWmiObject Ds Group with PowerShell Script Block
* GetDomainGroup with PowerShell Script Block
* Elevated Group Discovery with PowerView
* GetAdGroup with PowerShell
* GetDomainGroup with PowerShell
* GetWmiObject Ds Group with PowerShell

### CODE REVIEW

**Review by patel-bhavin — DISMISSED** [review]

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Domain Group Discovery with Adsisearcher :x:
- diskUsage: 155648
- runDuration: 1.087s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Domain Group Discovery with Adsisearcher :white_check_mark:
- diskUsage: 159744
- runDuration: 1.114s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Domain Group Discovery with Adsisearcher :white_check_mark:
- diskUsage: 159744
- runDuration: 1.352s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Domain Group Discovery With Dsquery :white_check_mark:
- diskUsage: 487424
- runDuration: 3.5380000000000003s
- scanCount: 2902

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Domain Group Discovery With Net :white_check_mark:
- diskUsage: 589824
- runDuration: 2.011s
- scanCount: 22

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Domain Group Discovery With Wmic :white_check_mark:
- diskUsage: 376832
- runDuration: 2.215s
- scanCount: 5

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Elevated Group Discovery With Net :white_check_mark:
- diskUsage: 638976
- runDuration: 2.407s
- scanCount: 19

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Elevated Group Discovery with PowerView :white_check_mark:
- diskUsage: 163840
- runDuration: 1.289s
- scanCount: 47

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Elevated Group Discovery With Wmic :x:
- diskUsage: 393216
- runDuration: 2.438s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetAdGroup with PowerShell Script Block :white_check_mark:
- diskUsage: 155648
- runDuration: 1.295s
- scanCount: 47

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Elevated Group Discovery With Wmic :white_check_mark:
- diskUsage: 409600
- runDuration: 2.507s
- scanCount: 5

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetDomainGroup with PowerShell :white_check_mark:
- diskUsage: 581632
- runDuration: 2.054s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetAdGroup with PowerShell :white_check_mark:
- diskUsage: 581632
- runDuration: 1.852s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetWmiObject Ds Group with PowerShell :white_check_mark:
- diskUsage: 376832
- runDuration: 2.195s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetDomainGroup with PowerShell Script Block :white_check_mark:
- diskUsage: 155648
- runDuration: 1.305s
- scanCount: 47

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetWmiObject Ds Group with PowerShell Script Block :white_check_mark:
- diskUsage: 163840
- runDuration: 1.0110000000000001s
- scanCount: 3

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
