### PR TITLE
Update misnamed eventid

### PR DESCRIPTION
**Pull request by pyth0n1c**
A number of YMLs had issues around the data_source object(s) in the YMLs.
Either the wrong named were used for Sysmon EventID (a space was accidentally included), the key in the YML was `data_sources` instead of `data_source`, or other minor issues.
This PR should resolve those issues.

### CODE REVIEW

**Review by ljstella — APPROVED** [review]
LGTM-

Failing CI jobs are currently unavoidable.

**Review by ljstella — CHANGES_REQUESTED** [review]
Does the change in `detections/application/windows_ad_privileged_group_modification.yml` require a version bump?

**Comment by pyth0n1c** [comment]
> Does the change in `detections/application/windows_ad_privileged_group_modification.yml` require a version bump?

Yes, nice catch! In fact this IS caught by the version-checking, it's just obfuscated by the other error on missing non-public content.
https://github.com/splunk/security_content/actions/runs/11060840382/job/30732226304#step:5:246

image

**Review by ljstella — APPROVED** [review]
:shipit:

**Pull request merged**
