### PR TITLE
WIP - 02Rel3

### PR DESCRIPTION
**Pull request by MHaggis**
## New Analytic Stories
- Silver Sparrow
- HAFNIUM Group

## New Detections
- Cobalt Strike Named Pipes (Passed)
- Suspicious DLLHost no Command Line Arguments (Passed)
- Suspicious GPUpdate no Command Line Arguments (Passed)
- Suspicious SearchProtocolHost no Command Line Arguments (Passed)
- Suspicious PlistBuddy Usage (Experimental)
- Suspicious SQLite3 LSAQuarantine Behavior (Experimental)
- Suspicious Curl Network Connection (Experimental)
- Ryuk Wake on LAN Command (Works, but batch not passing)
- Suspicious Scheduled Task from Public Directory (Passed)
- Fodhelper UAC Bypass (Passed)
- Eventvwr UAC Bypass (Passed)
- Any PowerShell DownloadString (Passed)
- Any PowerShell DownloadFile (Works, but batch not passing)
- Unified Messaging Service Spawning a Process (Experimental)
- Suspicious Unified Messaging Service File Writes (Experimental)
- Nishang PowershellTCPOneLine (Passed)
- W3WP Spawning Shells (Experimental)

## Updated Analytic Stories
- Cobalt Strike
- Suspicious MSHTA Activity (formatting issues)

## Updated Detections
- NTdsutil Export NTDS
- Suspicious MSBuild Path
- Suspicious MSBuild Rename
- Suspicious Microsoft Workflow Compiler Rename
- Detect Regsvr32 Application Control Bypass
- Windows DisableAntiSpyware Registry (Passed)

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Cobalt Strike Named Pipes :white_check_mark:
- diskUsage: 143360
- runDuration: 1.425s
- scanCount: 1112

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious GPUpdate no Command Line Arguments :white_check_mark:
- diskUsage: 286720
- runDuration: 10.315s
- scanCount: 17047

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Ryuk Wake on LAN Command :x:
- diskUsage: 483328
- runDuration: 1.723s
- scanCount: 7

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Ryuk Wake on LAN Command :x:
- diskUsage: 483328
- runDuration: 1.754s
- scanCount: 7

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious DLLHost no Command Line Arguments :white_check_mark:
- diskUsage: 286720
- runDuration: 10.312s
- scanCount: 17047

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious SearchProtocolHost no Command Line Arguments :white_check_mark:
- diskUsage: 290816
- runDuration: 10.306000000000001s
- scanCount: 17047

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

FodHelper UAC Bypass :white_check_mark:
- diskUsage: 405504
- runDuration: 5.328s
- scanCount: 6478

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Eventvwr UAC Bypass :white_check_mark:
- diskUsage: 364544
- runDuration: 4.748s
- scanCount: 6460

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Any Powershell DownloadFile :x:
- diskUsage: 389120
- runDuration: 11.305s
- scanCount: 16265

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows Disable Antispyware Reg :white_check_mark:
- diskUsage: 368640
- runDuration: 5.122s
- scanCount: 7143

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Any Powershell DownloadString :white_check_mark:
- diskUsage: 487424
- runDuration: 1.526s
- scanCount: 11

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Any Powershell DownloadFile :x:
- diskUsage: 495616
- runDuration: 1.5030000000000001s
- scanCount: 5

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Any Powershell DownloadFile :x:
- diskUsage: 401408
- runDuration: 12.275s
- scanCount: 16368

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious Scheduled Task from Public Directory :white_check_mark:
- diskUsage: 286720
- runDuration: 2.148s
- scanCount: 6

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious Scheduled Task from Public Directory :white_check_mark:
- diskUsage: 286720
- runDuration: 2.207s
- scanCount: 6

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Ryuk Wake on LAN Command :x:
- diskUsage: 479232
- runDuration: 1.607s
- scanCount: 11

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Any Powershell DownloadFile :x:
- diskUsage: 401408
- runDuration: 11.225s
- scanCount: 16368

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Nishang PowershellTCPOneLine :white_check_mark:
- diskUsage: 282624
- runDuration: 1.5170000000000001s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Ryuk Wake on LAN Command :x:
- diskUsage: 483328
- runDuration: 1.7690000000000001s
- scanCount: 7

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Ryuk Wake on LAN Command :x:
- diskUsage: 483328
- runDuration: 1.703s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Any Powershell DownloadFile :x:
- diskUsage: 401408
- runDuration: 14.116s
- scanCount: 21427

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
