### PR TITLE
Update xmrig

### PR DESCRIPTION
**Pull request by patel-bhavin**
This PR is combines all the attacker tools from : https://github.com/splunk/security_content/pull/1382/files into a single search based on lookup

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Attacker Tools On Endpoint :x:
- diskUsage: 98304
- runDuration: 0.004s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Attacker Tools On Endpoint :x:
- diskUsage: 98304
- runDuration: 0.003s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Attacker Tools On Endpoint :x:
- diskUsage: 98304
- runDuration: 0.003s
- scanCount: 0

**Comment by miskoSplunk** [comment]
@patel-bhavin  Seems good to me as something that will grow ... I'd suggest also putting some EXEs we blogged about ... just  read the draft about Trick bot - would be strange that we don't detect here things that we write about.

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Attacker Tools On Endpoint :x:
- diskUsage: 98304
- runDuration: 0.003s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Attacker Tools On Endpoint :x:
- diskUsage: 98304
- runDuration: 0.003s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Attacker Tools On Endpoint :x:
- diskUsage: 98304
- runDuration: 0.003s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Attacker Tools On Endpoint :x:
- diskUsage: 98304
- runDuration: 0.003s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Attacker Tools On Endpoint :x:
- diskUsage: 98304
- runDuration: 0.003s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Attacker Tools On Endpoint :x:
- diskUsage: 98304
- runDuration: 0.003s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Attacker Tools On Endpoint :x:
- diskUsage: 98304
- runDuration: 0.003s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Attacker Tools On Endpoint :x:
- diskUsage: 98304
- runDuration: 0.003s
- scanCount: 0

**Pull request closed without merging**
