### PR TITLE
Nterl0k [T1098]  - O365 Azure Workload things

### PR DESCRIPTION
**Pull request by nterl0k**
### Details

This PR includes a number of detections written for the O365 Azure Active Directory workload from the universal audit log (o365 management activity). A few of the detections are 1:1 duplicates of existing ESCU content or expands coverage, only adapted for a slightly easier to access data source. Other detections are focused on monitoring sensitive changes to a number of Azure external access settings.

- O365 Privileged Role Assigned (duplicate [Azure AD Privileged Role Assigned](https://splunkresearch.com/cloud/a28f0bc3-3400-4a6e-a2da-89b9e95f0d2a/) and [O365 High Privilege Role Granted](https://splunkresearch.com/cloud/e78a1037-4548-4072-bb1b-ad99ae416426/))
- O365 Privileged Role Assigned To Service Principal (duplicate -[Azure AD Privileged Role Assigned to Service Principal](https://splunkresearch.com/cloud/5dfaa3d3-e2e4-4053-8252-16d9ee528c41/))
- O365 External Guest User Invited (duplicate - [Azure AD External Guest User Invited](https://splunkresearch.com/cloud/c1fb4edb-cab1-4359-9b40-925ffd797fb5/))
- O365 Cross-Tenant Access Change (New)
- O365 External Identity Policy Changed (New)
- O365 Application Available To Other Tenants (New)

These detections also extract either the User Principal or Service Principal from the Actor field. Recommend profile your azure environments to populate this data into Assets and Identities.

This PR also includes a number of changes to the "lookups/privileged_azure_ad_roles" lookup and lookup definition, mainly for the purpose of including more known privileged Azure groups relevant in 2024, none of the previous groups were removed.

An additional column has been added to also include the "Template ID" for all groups, which is an immutable GUID used by MS. This GUI should allow for more accurate detections if/when Microsoft changes the string values of well-known objects. (https://learn.microsoft.com/en-us/azure/active-directory/roles/permissions-reference)

Changes to lookup should be backward compatible with existing content.

pending data PR https://github.com/splunk/attack_data/pull/891

### Checklist

- [ ] Validate name matches `<platform>_<mitre att&ck technique>_<short description>` nomenclature
- [ ] [CI/CD](https://github.com/splunk/security_content/actions) jobs passed ✔️ 
- [ ] Validated SPL logic.
- [ ] Validated tags, description, and how to implement.
- [ ] Verified references match analytic.

### CODE REVIEW

**Comment by ljstella** [comment]
Hey @nterl0k ! Long time no talk! Sorry for letting this sit as long as it did. We're working through the backlog now with a bit more focus and ease now that primary development has shifted back here.

Summary for the commit I added: 
1) Build was failing due to some formatting in the `search:` bit for 6 detections. The second line of these all used `'` single quotes around fields which appeared to close the initial quote around the full search. The solution here was adding the `>` bracket to force the folded style of multiline string, and then indenting each of those blocks.
2) Once those were finished, validate was able to run the actual validation checks against the rest of the fields. This raised a series of errors related to the `tags.asset_type` field, which we've adjusted from `Office 365` to match the expected value of `O365 Tenant`.

As I'm writing this, unit testing is still running but the build steps have all passed! Hoping to get this merged for our next release! 

Cheers!

**Comment by nterl0k** [comment]
That's groovy... I'll have to remember the > formatting for in the future.


I wasn't sure on the asset type so I just copied from one of the existing detections for o365..

I transfer my blame elsewhere :)



Regards,

Steven.



-------- Original message --------
From: Lou Stella ***@***.***>
Date: 7/24/24 5:33 PM (GMT-05:00)
To: splunk/security_content ***@***.***>
Cc: Steven Dick ***@***.***>, Mention ***@***.***>
Subject: Re: [splunk/security_content] Nterl0k [T1098] - O365 Azure Workload things (PR #2999)


Hey @nterl0k<https://github.com/nterl0k> ! Long time no talk! Sorry for letting this sit as long as it did. We're working through the backlog now with a bit more focus and ease now that primary development has shifted back here.

Summary for the commit I added:

  1.  Build was failing due to some formatting in the search: bit for 6 detections. The second line of these all used ' single quotes around fields which appeared to close the initial quote around the full search. The solution here was adding the > bracket to force the folded style of multiline string, and then indenting each of those blocks.
  2.  Once those were finished, validate was able to run the actual validation checks against the rest of the fields. This raised a series of errors related to the tags.asset_type field, which we've adjusted from Office 365 to match the expected value of O365 Tenant.

As I'm writing this, unit testing is still running but the build steps have all passed! Hoping to get this merged for our next release!

Cheers!

**Comment by ljstella** [comment]
Alright, testing now passes entirely for these. Before we merge, I _think_ we just need to tweak the lookup definition & lookup filename so that on updates of the app to the version that include this, the new lookup is put in place. Other than that, we should be set to merge. Thank you @nterl0k !

**Review by ljstella — DISMISSED** [review]
:shipit: 

Thanks again @nterl0k for this awesome contribution!

**Comment by nterl0k** [comment]
Happy to contribute... I've got more on the way, spare time has been lacking lately on my end too.
________________________________

**Review by ljstella — APPROVED** [review]
:shipit:

**Pull request merged**
