### PR TITLE
Add Potential password in username detection

### PR DESCRIPTION
**Pull request by inspired**
# PR Template for new Detections

For Authors:
- [x] Make sure that CI/CD [detection-testing and build-and-validate](https://github.com/splunk/security_content/actions) jobs passed ✔️. 

For Reviewers:
- [ ] Verify CI/CD jobs have passed without errors.
- [ ] Validate SPL logic.
- [ ] Validate tags, description, and how to implement.
- [ ] Validate name matches `<platform>_<mitre att&ck technique>_<short description>`
- [ ] Verify references match analytic.
- [ ] Is there an Atomic Test?

### CODE REVIEW

**Comment by patel-bhavin** [comment]
@inspired : Hey!  thank you for the PR. Do you have a test dataset for this detection that you can share in our attack_data repo?  since there is no test file or attack_data for this detection, it is failing our current detecting-testing pipeline in the CI. 

If not, can you move this detection file to the experimental folder?

**Comment by inspired** [comment]
@patel-bhavin PR for dataset now in attack_data. Updated detection with pointers to attack_data. Let me know if anything else is missing.

**Comment by patel-bhavin** [comment]
thank you for updating the PR. since this PR is from a fork, we think that out detecting testing CI and other workflows are not working as intended. We might create a duplicate PR of this to run it via our CI and get it merged!  Will keep you posted :)

**Comment by patel-bhavin** [comment]
created a duplicate PR: https://github.com/splunk/security_content/pull/2220

**Comment by patel-bhavin** [comment]
Hello @inspired : Sorry for the delay i getting to testing and validating this PR. When i try to test the search manually, it complains regarding the lookup used in the SPL. Can you please provide us the lookup file?

image

**Comment by patel-bhavin** [comment]
thanks for providing the details on slack. the changes are incorporated into the duplicate 
https://github.com/splunk/security_content/pull/2220

**Pull request closed without merging**
