### PR TITLE
Exchange Server Batch Testing

### PR DESCRIPTION
**Pull request by MHaggis**
## Detections Updated
- Unified Messaging Service Spawning a Process (Passed)
- W3WP Spawning Shell (Passed)

image
image

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Unified Messaging Service Spawning a Process :x:
- diskUsage: 417792
- runDuration: 59.709s
- scanCount: 93547

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

W3WP Spawning Shell :x:
- diskUsage: 409600
- runDuration: 58.167s
- scanCount: 93547

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Unified Messaging Service Spawning a Process :x:
- diskUsage: 417792
- runDuration: 1.311s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Unified Messaging Service Spawning a Process :x:
- diskUsage: 417792
- runDuration: 1.285s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

W3WP Spawning Shell :white_check_mark:
- diskUsage: 413696
- runDuration: 33.372s
- scanCount: 49626

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Unified Messaging Service Spawning a Process :white_check_mark:
- diskUsage: 421888
- runDuration: 103.13s
- scanCount: 156565

**Review by josehelps — APPROVED** [review]

**Pull request merged**
