### PR TITLE
privilege_escalation_persistence

### PR DESCRIPTION
**Pull request by tccontre**
## New Detections CARS-Mitre

- screensaver_event_trigger_execution.yml (passed)
- change_default_file_association.yml (passed)
- logon_script_event_trigger_execution.yml (passed)
- verclsid_clsid_execution.yml (passed)
- active_setup_registry_autostart.yml (passed)
- disable_uac_remote_restriction.yml (passed)
- time_provider_persistence_registry.yml (passed)
- vbscript_execution_using_wscript_app.yml  (passed)
- msbuild_suspicious_spawned_by_script_process.yml (passed)
- powershell_reflective_load.yml (passed)
- regsvr32_silent_param_dll_loading.yml (passed)
- disable_security_logs_using_minint_registry.yml (passed)
- enable_wdigest_uselogoncredential_registry.yml (passed)
- rundll32_shimcache_flush.yml (passed)
- suspicious_copy_on_system32.yml (passed)
- sdelete_application_execution.yml (passed)
- wscript_or_cscript_suspicious_child_process.yml (passed)
- etw_registry_disabled.yml (passed)

## Experimental ( it works in manual test but keep failing in AWS test) 
- print_processor_registry_autostart.yml

## Modified Existing Detections

- registry_keys_used_for_persistence.yml 

## macro
- process_copy.yml
- process_verclsid.yml
- process_sdelete.yml

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Verclsid CLSID Execution :white_check_mark:
- diskUsage: 634880
- runDuration: 8.813s
- scanCount: 12056

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Manual datasets generation for Screensaver Event Trigger Execution. :white_check_mark:
- diskUsage: 520192
- runDuration: 2.285s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Logon Script Event Trigger Execution :white_check_mark:
- diskUsage: 524288
- runDuration: 2.138s
- scanCount: 9

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Change Default File Association :white_check_mark:
- diskUsage: 512000
- runDuration: 1.491s
- scanCount: 4

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Active Setup Registry Autostart :white_check_mark:
- diskUsage: 536576
- runDuration: 9.101s
- scanCount: 14361

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Print Processor Registry Autostart :x:
- diskUsage: 491520
- runDuration: 1.723s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Print Processor Registry Autostart :x:
- diskUsage: 491520
- runDuration: 1.834s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Print Processor Registry Autostart :x:
- diskUsage: 491520
- runDuration: 1.601s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Time Provider Persistence Registry :white_check_mark:
- diskUsage: 503808
- runDuration: 1.778s
- scanCount: 54

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Disable UAC Remote Restriction :white_check_mark:
- diskUsage: 507904
- runDuration: 2.499s
- scanCount: 7

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Vbscript Execution Using Wscript App :white_check_mark:
- diskUsage: 442368
- runDuration: 5.63s
- scanCount: 6460

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Print Processor Registry Autostart :x:
- diskUsage: 475136
- runDuration: 2.555s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Print Processor Registry Autostart :x:
- diskUsage: 483328
- runDuration: 2.168s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Powershell Reflective Load :x:
- diskUsage: 155648
- runDuration: 1.215s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Regsvr32 Silent Param Dll Loading :white_check_mark:
- diskUsage: 487424
- runDuration: 9.197000000000001s
- scanCount: 6706

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

MSBuild Suspicious Spawned By Script Process :x:
- diskUsage: 491520
- runDuration: 1.843s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

MSBuild Suspicious Spawned By Script Process :white_check_mark:
- diskUsage: 520192
- runDuration: 7.457s
- scanCount: 9660

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Powershell Reflective Load :white_check_mark:
- diskUsage: 163840
- runDuration: 1.809s
- scanCount: 6

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Print Processor Registry Autostart :x:
- diskUsage: 483328
- runDuration: 2.04s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious Copy on System32 :white_check_mark:
- diskUsage: 401408
- runDuration: 7.4750000000000005s
- scanCount: 10496

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Rundll32 Shimcache Flush :white_check_mark:
- diskUsage: 372736
- runDuration: 3.6590000000000003s
- scanCount: 3516

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Enable WDigest UseLogonCredential Registry :white_check_mark:
- diskUsage: 516096
- runDuration: 1.96s
- scanCount: 8

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Disable Security Logs Using MiniNt Registry :white_check_mark:
- diskUsage: 512000
- runDuration: 1.706s
- scanCount: 8

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Wscript Or Cscript Suspicious Child Process :white_check_mark:
- diskUsage: 466944
- runDuration: 7.6290000000000004s
- scanCount: 6459

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Sdelete Application Execution :white_check_mark:
- diskUsage: 466944
- runDuration: 5.273s
- scanCount: 5471

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Print Processor Registry Autostart :x:
- diskUsage: 479232
- runDuration: 2.06s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

ETW Registry Disabled :white_check_mark:
- diskUsage: 516096
- runDuration: 2.337s
- scanCount: 3

**Review by MHaggis — DISMISSED** [review]

**Review by mvelazc0 — APPROVED** [review]

**Pull request merged**
