### PR TITLE
Lateral Movement Content Update #3

### PR DESCRIPTION
**Pull request by mvelazc0**
## New Detections

- Impacket Lateral Movement Commandline Parameters
- Windows Service Created Within Public Path
- Wmiprsve LOLBAS Execution Process Spawn
- Services LOLBAS Execution Process Spawn
- Svchost LOLBAS Execution Process Spawn 
- Wsmprovhost LOLBAS Execution Process Spawn
- Mmc LOLBAS Execution Process Spawn

All detections have passed automated testing

## Updated Detections

- Windows Service Created With Suspicious Service Path

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Impacket Lateral Movement Commandline Parameters :white_check_mark:
- diskUsage: 352256
- runDuration: 2.332s
- scanCount: 234

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows Service Created With Suspicious Service Path :white_check_mark:
- diskUsage: 172032
- runDuration: 0.996s
- scanCount: 21

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Services.exe LOLBAS Execution Process Spawn :white_check_mark:
- diskUsage: 679936
- runDuration: 4.189s
- scanCount: 3875

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Mmc.exe LOLBAS Execution Process Spawn :white_check_mark:
- diskUsage: 708608
- runDuration: 3.684s
- scanCount: 3279

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Wmiprsve.exe LOLBAS Execution Process Spawn :white_check_mark:
- diskUsage: 708608
- runDuration: 3.732s
- scanCount: 3234

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Wsmprovhost.exe LOLBAS Execution Process Spawn :white_check_mark:
- diskUsage: 708608
- runDuration: 4.249s
- scanCount: 3906

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Svchost.exe LOLBAS Execution Process Spawn :x:
- diskUsage: 692224
- runDuration: 3.799s
- scanCount: 3327

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Svchost.exe LOLBAS Execution Process Spawn :white_check_mark:
- diskUsage: 720896
- runDuration: 2.101s
- scanCount: 455

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows Service Created Within Public Path :white_check_mark:
- diskUsage: 172032
- runDuration: 1.24s
- scanCount: 1

**Review by MHaggis — APPROVED** [review]

**Pull request merged**
