### PR TITLE
Searches with sub-searches improvements / Proc_Guid Replacement 

### PR DESCRIPTION
**Pull request by nterl0k**
### Details

Pull request contains a number of code refactoring changes to correlations that use an unrestricted sub-search/join (the non-CIM field "proc_guid" is used in them) which results in either inaccurate or no results due to sub-search limitations. Production environments can easily overrun 50k processes per/hr, which breaks this type of correlation.

Refactoring the code to place the larger/unlimited search first, with the limited scope search in the join/sub-search allows these searches to function as intended.

This is related to #2458 and #2281 

General template for all of these changes follows this SPL

```
search: '| tstats `security_content_summariesonly` count min(_time) AS firstTime max(_time) AS lastTime FROM datamodel=Endpoint.Processes BY _time span=1h Processes.user Processes.process_id Processes.process_name Processes.process Processes.process_path Processes.dest Processes.parent_process_name Processes.parent_process Processes.process_guid
| `drop_dm_object_name(Processes)` 
| join process_guid [
| tstats `security_content_summariesonly` count FROM datamodel=Endpoint.Registry WHERE (### CHANGE ME TO REG VALUES ###) BY _time span=1h Registry.registry_path Registry.registry_key_name Registry.registry_value_name Registry.registry_value_data Registry.process_guid 
| `drop_dm_object_name(Registry)`] 
| fields firstTime lastTime dest user parent_process_name parent_process process_name process_path process registry_key_name registry_path registry_value_name registry_value_data process_guid
| where isnotnull(registry_value_data)
| `security_content_ctime(firstTime)` 
| `security_content_ctime(lastTime)`
| `### CHANGE ME TO FILTER MACRO ###`'
```

### Checklist

- [ ] Validate name matches `<platform>_<mitre att&ck technique>_<short description>` nomenclature
- [ ] [CI/CD](https://github.com/splunk/security_content/actions) jobs passed ✔️ 
- [ ] Validated SPL logic.
- [ ] Validated tags, description, and how to implement.
- [ ] Verified references match analytic.

### CODE REVIEW

**Comment by tccontre** [comment]
[Update set_default_powershell_execution_policy_to_unrestricted_or_byp…](https://github.com/splunk/security_content/pull/2459/commits/5160673e901992f7939d11dbb064dc1ea78e2ff7) to continue the build and validation

**Comment by nterl0k** [comment]
> [Update set_default_powershell_execution_policy_to_unrestricted_or_byp…](https://github.com/splunk/security_content/pull/2459/commits/5160673e901992f7939d11dbb064dc1ea78e2ff7) to continue the build and validation

Interesting, do you need me to fix the indent?

**Comment by tccontre** [comment]
oh no worries i already did. ;)

**Comment by nterl0k** [comment]
Foiled by formatting again, curse you yaml.

**Comment by nterl0k** [comment]
Accidental update, sorry about that.

**Comment by patel-bhavin** [comment]
@nterl0k @tccontre : are we still working off this PR or these updates have been merged in some other branch?

**Comment by nterl0k** [comment]
@patel-bhavin I haven't pushed these to any other branch. 

TBH I probably should have done multiple smaller PR. Given they're all existing detections, I figured validation would be a quick and easy affair.

**Comment by patel-bhavin** [comment]
Hello @nterl0k : We have ported all these changes into a new PR: https://github.com/splunk/security_content/pull/2516 and looks like all the changes you made passed the detection testing. Thank you for an excellent PR!

**Pull request closed without merging**
