### PR TITLE
May The Haag Be With You

### PR DESCRIPTION
**Pull request by MHaggis**
## New Analytics

- Net Localgroup Discovery (Passed)
- Wmic Group Discovery (Passed)
- Powershell Get LocalGroup Discovery with Script Block Logging (Passed)
- PowerShell Get LocalGroup Discovery (Passed)
- Get WMIObject Group Discovery with Script Block Logging (Passed)
- Get WMIObject Group Discovery (Passed)

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Get WMIObject Group Discovery :white_check_mark:
- diskUsage: 598016
- runDuration: 2.008s
- scanCount: 5

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Get WMIObject Group Discovery with Script Block Logging :white_check_mark:
- diskUsage: 163840
- runDuration: 1.115s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Net Localgroup Discovery :white_check_mark:
- diskUsage: 491520
- runDuration: 33.039s
- scanCount: 61922

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

PowerShell Get LocalGroup Discovery :x:
- diskUsage: 585728
- runDuration: 2.192s
- scanCount: 11

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Powershell Get LocalGroup Discovery with Script Block Logging :white_check_mark:
- diskUsage: 159744
- runDuration: 1.252s
- scanCount: 17

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Wmic Group Discovery :white_check_mark:
- diskUsage: 364544
- runDuration: 2.339s
- scanCount: 93

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

PowerShell Get LocalGroup Discovery :white_check_mark:
- diskUsage: 589824
- runDuration: 2.121s
- scanCount: 13

**Review by mvelazc0 — APPROVED** [review]

**Pull request merged**
