### PR TITLE
Detect LOLBAS with Outbound Network Traffic

### PR DESCRIPTION
**Pull request by nterl0k**
### Details

Adds an additional detection for "Living Off the Land" story for LOLBAS executables with with outbound network traffic.

image

### Checklist

- [ ] Validate name matches `<platform>_<mitre att&ck technique>_<short description>` nomenclature
- [ ] [CI/CD](https://github.com/splunk/security_content/actions) jobs passed ✔️ 
- [ ] Validated SPL logic.
- [ ] Validated tags, description, and how to implement.
- [ ] Verified references match analytic.

### CODE REVIEW

**Comment by patel-bhavin** [comment]
Hello @nterl0k : Thank you for contributing this detection. We try out best to test all our content using a corresponding attack data file( eg: https://github.com/splunk/security_content/blob/388fe34d7bc4de62b324b69d6dc43726eebd35b6/detections/endpoint/7zip_commandline_to_smb_share_path.yml#L37
)

Can you share a _raw data that has both the endpoint and network event ? 
Thanks again

**Comment by nterl0k** [comment]
@patel-bhavin shouldn't be an issue, let me see about generating it in my lab. Where would be the best place to upload the _raw?

**Comment by patel-bhavin** [comment]
Please create a PR to our attack data repo and  upload the _raw file  in the appropriate attack_data folder here :
https://github.com/splunk/attack_data/tree/master/datasets/attack_techniques

It also needs a yaml file describing the log files: example: https://github.com/splunk/attack_data/blob/master/datasets/attack_techniques/T1003.002/serioussam/serioussam.yml

**Comment by nterl0k** [comment]
@patel-bhavin  Sorry for the delay on this, I threw some data at the attack_data repo and updated the dataset here.

https://github.com/splunk/attack_data/pull/789

**Comment by patel-bhavin** [comment]
I have updated the datasets, thanks for sharing that. added this detection to https://github.com/splunk/security_content/pull/2528 for testing and minor changes! thank you for submitting all the required files! Very much appreciated

**Pull request closed without merging**
