### PR TITLE
Office 365 Detections

### PR DESCRIPTION
**Pull request by P4T12ICK**
Story File description and narrative missing

Bhavin: Adding detection and test file for "High Number of Login Failures from a single source"

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

O365 Suspicious Rights Delegation :white_check_mark:
- diskUsage: 126976
- runDuration: 0.548s
- scanCount: 4

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

O365 Suspicious Rights Delegation :white_check_mark:
- diskUsage: 126976
- runDuration: 0.561s
- scanCount: 4

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

O365 Suspicious User Email Forwarding :white_check_mark:
- diskUsage: 126976
- runDuration: 0.545s
- scanCount: 77

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

O365 Suspicious Admin Email Forwarding :white_check_mark:
- diskUsage: 122880
- runDuration: 0.541s
- scanCount: 77

**Comment by patel-bhavin** [comment]
@miskoSplunk : Good eye, let me chat with @rosplk tomorrow and get this resolved.

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

O365 Disable MFA :white_check_mark:
- diskUsage: 118784
- runDuration: 0.549s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

O365 Excessive Authentication Failures Alert :x:
- diskUsage: 122880
- runDuration: 0.532s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

O365 PST export alert :white_check_mark:
- diskUsage: 118784
- runDuration: 0.556s
- scanCount: 14

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

O365 Excessive Authentication Failures Alert :white_check_mark:
- diskUsage: 126976
- runDuration: 0.5650000000000001s
- scanCount: 132

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

High Number of Login Failures from a single source :x:
- diskUsage: 126976
- runDuration: 0.518s
- scanCount: 0

**Comment by Rickbale606** [comment]
To do in Word what you seem to be referring to go to Tools> Protect Document... then clear the check for Privacy - Remove personal information from this file on save. Note that this is a per-document setting, not one that is global for the program.

**Review by josehelps — APPROVED** [review]

**Comment by josehelps** [comment]
@Rickbale606 not sure I fully understood your comment, where you meant to put that somewhere else? :smile:

**Pull request merged**
