### PR TITLE
linux_persist_priv_batch_1

### PR DESCRIPTION
**Pull request by tccontre**
## Cronjob and At scheduler technique

- linux_add_files_in_known_crontab_directories.yml (passed)
- linux_at_allow_config_file_creation.yml (passed)
- linux_at_application_execution.yml (passed)
- linux_edit_cron_table_parameter.yml (passed)
- linux_possible_append_command_to_at_allow_config_file.yml
- linux_possible_append_cronjob_entry_on_existing_cronjob_file.yml
- linux_possible_cronjob_modification_with_editor.yml (passed)

### New Analytic Stories

- linux_persistence_techniques.yml
- linux_privilege_escalation.yml

## Docker Testing (All detection passed - success.csv)
Screenshot 2022-01-05 at 15 34 02

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Possible Cronjob Modification With Editor :white_check_mark:
- diskUsage: 380928
- runDuration: 34.307s
- scanCount: 59363

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Possible Append Cronjob Entry on Existing Cronjob File :x:
- diskUsage: 385024
- runDuration: 32.044000000000004s
- scanCount: 59364

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Possible Append Command To At Allow Config File :x:
- diskUsage: 376832
- runDuration: 28.400000000000002s
- scanCount: 53699

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Edit Cron Table Parameter :white_check_mark:
- diskUsage: 610304
- runDuration: 31.225s
- scanCount: 57784

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Possible Append Cronjob Entry on Existing Cronjob File :x:
- diskUsage: 368640
- runDuration: 32.667s
- scanCount: 59363

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux At Application Execution :white_check_mark:
- diskUsage: 430080
- runDuration: 29.521s
- scanCount: 53698

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux At Allow Config File Creation :white_check_mark:
- diskUsage: 425984
- runDuration: 28.237000000000002s
- scanCount: 53333

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Add Files In Known Crontab Directories :white_check_mark:
- diskUsage: 475136
- runDuration: 34.256s
- scanCount: 59365

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Possible Append Command To At Allow Config File :x:
- diskUsage: 376832
- runDuration: 29.89s
- scanCount: 53699

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Possible Append Command To At Allow Config File :x:
- diskUsage: 348160
- runDuration: 27.754s
- scanCount: 53698

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
