### PR TITLE
Nterl0k T1564.004 - Nothing about this ADS up.

### PR DESCRIPTION
**Pull request by nterl0k**
### Details
NTFS Alternate Data Stream abuse techniques

See https://github.com/splunk/attack_data/pull/850 for data as well as a TTP data generation script.

PR has 3 detections
1 detection for executable code stored in an ADS
1 detection for commonly abused processes with command line evidence of execution from ADS.
1 detection for base64 code stored in an ADS, with bonus lazy base64 decoding macro/lookup (optional can be removed but is convenient for analysts).

image

### Checklist

- [ ] Validate name matches `<platform>_<mitre att&ck technique>_<short description>` nomenclature
- [ ] [CI/CD](https://github.com/splunk/security_content/actions) jobs passed ✔️ 
- [ ] Validated SPL logic.
- [ ] Validated tags, description, and how to implement.
- [ ] Verified references match analytic.

### CODE REVIEW

**Comment by patel-bhavin** [comment]
thanks @nterl0k ! We are testing this in our dev environment and left some comments on the attack_data PR!

**Comment by nterl0k** [comment]
No problem, changes already committed to the attack_data PR

Regards,

Steven.



-------- Original message --------
From: Bhavin Patel ***@***.***>
Date: 12/11/23 5:42 PM (GMT-05:00)
To: splunk/security_content ***@***.***>
Cc: Steven Dick ***@***.***>, Mention ***@***.***>
Subject: Re: [splunk/security_content] Nterl0k T1564.004 - Nothing about this ADS up. (PR #2914)


thanks @nterl0k<https://github.com/nterl0k> ! We are testing this in our dev environment and left some comments on the attack_data PR!

**Comment by patel-bhavin** [comment]
image

updated and tested and these detections look good!

**Comment by patel-bhavin** [comment]
we will ship this in ESCU 4.19.0 :)

**Comment by patel-bhavin** [comment]
The detections is in PR have now been merged and published! Thanks @nterl0k

**Pull request closed without merging**
