### PR TITLE
PR for Patrick Detection Testing

### PR DESCRIPTION
**Pull request by P4T12ICK**
PR

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Prohibited Applications Spawning cmd exe :white_check_mark:
- diskUsage: 352256
- runDuration: 1.28s
- scanCount: 496

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect processes used for System Network Configuration Discovery :x:
- diskUsage: 356352
- runDuration: 7.118s
- scanCount: 10000

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect processes used for System Network Configuration Discovery :white_check_mark:
- diskUsage: 360448
- runDuration: 5.6530000000000005s
- scanCount: 7680

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect PsExec With accepteula Flag :x:
- diskUsage: 339968
- runDuration: 4.6000000000000005s
- scanCount: 6153

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Use of cmd exe to Launch Script Interpreters :white_check_mark:
- diskUsage: 360448
- runDuration: 1.441s
- scanCount: 853

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect PsExec With accepteula Flag :white_check_mark:
- diskUsage: 339968
- runDuration: 4.652s
- scanCount: 6153

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Disabling Remote User Account Control :x:
- diskUsage: 241664
- runDuration: 0.529s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Disabling Remote User Account Control :x:
- diskUsage: 241664
- runDuration: 0.52s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Disabling Remote User Account Control :white_check_mark:
- diskUsage: 249856
- runDuration: 4.245s
- scanCount: 6460

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Execution of File with Multiple Extensions :white_check_mark:
- diskUsage: 434176
- runDuration: 1.323s
- scanCount: 27

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

File with Samsam Extension :white_check_mark:
- diskUsage: 241664
- runDuration: 5.296s
- scanCount: 8286

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

First Time Seen Child Process of Zoom :white_check_mark:
- diskUsage: 360448
- runDuration: 6.546s
- scanCount: 8985

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Hiding Files And Directories With Attrib exe :white_check_mark:
- diskUsage: 438272
- runDuration: 5.197s
- scanCount: 6927

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Malicious PowerShell Process - Connect To Internet With Hidden Window :white_check_mark:
- diskUsage: 442368
- runDuration: 1.223s
- scanCount: 5

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Malicious PowerShell Process - Execution Policy Bypass :white_check_mark:
- diskUsage: 434176
- runDuration: 4.537s
- scanCount: 5702

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Monitor Registry Keys for Print Monitors :white_check_mark:
- diskUsage: 487424
- runDuration: 5.059s
- scanCount: 6324

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Overwriting Accessibility Binaries :white_check_mark:
- diskUsage: 299008
- runDuration: 0.711s
- scanCount: 31

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Processes created by netsh :x:
- diskUsage: 348160
- runDuration: 0.985s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Processes created by netsh :white_check_mark:
- diskUsage: 344064
- runDuration: 9.237s
- scanCount: 13983

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Reg exe Manipulating Windows Services Registry Keys :x:
- diskUsage: 344064
- runDuration: 1.225s
- scanCount: 25

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Reg exe Manipulating Windows Services Registry Keys :white_check_mark:
- diskUsage: 348160
- runDuration: 3.434s
- scanCount: 3864

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Registry Keys for Creating SHIM Databases :white_check_mark:
- diskUsage: 249856
- runDuration: 4.027s
- scanCount: 6073

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Shim Database Installation With Suspicious Parameters :white_check_mark:
- diskUsage: 348160
- runDuration: 4.714s
- scanCount: 6078

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Shim Database Installation With Suspicious Parameters :white_check_mark:
- diskUsage: 348160
- runDuration: 4.527s
- scanCount: 6078

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Shim Database Installation With Suspicious Parameters :white_check_mark:
- diskUsage: 348160
- runDuration: 4.808s
- scanCount: 6078

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Reg exe Manipulating Windows Services Registry Keys :white_check_mark:
- diskUsage: 348160
- runDuration: 3.4330000000000003s
- scanCount: 3864

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Registry Keys for Creating SHIM Databases :white_check_mark:
- diskUsage: 249856
- runDuration: 4.059s
- scanCount: 6073

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Registry Keys Used For Persistence :white_check_mark:
- diskUsage: 315392
- runDuration: 3.918s
- scanCount: 6031

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Registry Keys Used For Privilege Escalation :white_check_mark:
- diskUsage: 258048
- runDuration: 3.989s
- scanCount: 6134

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Remote Process Instantiation via WMI :white_check_mark:
- diskUsage: 425984
- runDuration: 1.289s
- scanCount: 8

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

RunDLL Loading DLL By Ordinal :white_check_mark:
- diskUsage: 348160
- runDuration: 6.963s
- scanCount: 9584

**Review by patel-bhavin — DISMISSED** [review]

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
