### PR TITLE
k8s scanner detection

### PR DESCRIPTION
**Pull request by P4T12ICK**
k8s scanner detection

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Kubernetes Scanner Image Pulling :x:
- diskUsage: 163840
- runDuration: 0.9460000000000001s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Kubernetes Scanner Image Pulling :x:
- diskUsage: 163840
- runDuration: 1.164s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Kubernetes Scanner Image Pulling :x:
- diskUsage: 159744
- runDuration: 1.025s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Kubernetes Scanner Image Pulling :x:
- diskUsage: 159744
- runDuration: 1.718s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Kubernetes Scanner Image Pulling :white_check_mark:
- diskUsage: 163840
- runDuration: 1.177s
- scanCount: 1

**Review by tccontre — DISMISSED** [review]

**Review by tccontre — DISMISSED** [review]

**Pull request merged**
