### PR TITLE
The Wonderful Wizard of Haag

### PR DESCRIPTION
**Pull request by MHaggis**
## Prerequisites 
This PR requires the latest CIM 4.20 to be installed. In addition, whatever EDR product in use, the TA must utilize the latest `original_file_name` field to use the enhanced datamodel queries found here. The latest [Sysmon TA](https://splunkbase.splunk.com/app/5709/) has adopted original_file_name and maps accordingly. 

In addition, this PR brings in the use of macros for commonly used process_name's used. For example, 
`process_powershell` macro equates to:

`(Processes.process_name=pwsh.exe OR Processes.process_name=sqlps.exe OR Processes.process_name=sqltoolsps.exe OR Processes.process_name=powershell.exe OR Processes.process_name=powershell_ise.exe OR Processes.original_file_name=pwsh.dll OR Processes.original_file_name=PowerShell.EXE OR Processes.original_file_name=powershell_ise.EXE)`

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Renamed rundll32.exe Rename :white_check_mark:
- diskUsage: 593920
- runDuration: 9.233s
- scanCount: 13107

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect renamed msbuild execution :x:
- diskUsage: 593920
- runDuration: 3.565s
- scanCount: 3193

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect renamed msbuild execution :x:
- diskUsage: 593920
- runDuration: 3.685s
- scanCount: 3193

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect renamed msbuild execution :x:
- diskUsage: 593920
- runDuration: 3.962s
- scanCount: 3193

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious Rundll32 startw :white_check_mark:
- diskUsage: 491520
- runDuration: 8.812s
- scanCount: 13107

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Renamed RClone :white_check_mark:
- diskUsage: 184320
- runDuration: 1.462s
- scanCount: 61

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Renamed PSExec :white_check_mark:
- diskUsage: 602112
- runDuration: 6.221s
- scanCount: 7980

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Renamed WinRAR :x:
- diskUsage: 176128
- runDuration: 0.005s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Renamed WinRAR :x:
- diskUsage: 176128
- runDuration: 0.005s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Renamed 7-Zip :white_check_mark:
- diskUsage: 598016
- runDuration: 10.562s
- scanCount: 17070

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect microsoft.workflow.compiler.exe rename :x:
- diskUsage: 569344
- runDuration: 1.742s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect HTML Help Renamed :x:
- diskUsage: 593920
- runDuration: 5.165s
- scanCount: 6603

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect HTML Help Renamed :white_check_mark:
- diskUsage: 598016
- runDuration: 4.989s
- scanCount: 6603

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect microsoft.workflow.compiler.exe rename :white_check_mark:
- diskUsage: 602112
- runDuration: 9.346s
- scanCount: 14217

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect microsoft.workflow.compiler.exe usage :x:
- diskUsage: 479232
- runDuration: 2.2560000000000002s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect microsoft.workflow.compiler.exe usage :white_check_mark:
- diskUsage: 499712
- runDuration: 10.370000000000001s
- scanCount: 14217

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Renamed PSExec :white_check_mark:
- diskUsage: 602112
- runDuration: 6.042s
- scanCount: 7981

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Renamed WinRAR :white_check_mark:
- diskUsage: 598016
- runDuration: 10.421s
- scanCount: 17069

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect renamed msbuild execution :x:
- diskUsage: 593920
- runDuration: 3.485s
- scanCount: 3193

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect SharpHound Usage :x:
- diskUsage: 491520
- runDuration: 6.761s
- scanCount: 9406

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect SharpHound Usage :white_check_mark:
- diskUsage: 499712
- runDuration: 6.421s
- scanCount: 9406

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Any Powershell DownloadFile :x:
- diskUsage: 516096
- runDuration: 13.575000000000001s
- scanCount: 21714

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

BCDEdit Failure Recovery Modification :x:
- diskUsage: 581632
- runDuration: 3.5780000000000003s
- scanCount: 66

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Certutil exe certificate extraction :white_check_mark:
- diskUsage: 581632
- runDuration: 2.274s
- scanCount: 13

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Common Ransomware Notes :x:
- diskUsage: 495616
- runDuration: 1.707s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Account Discovery With Net App :white_check_mark:
- diskUsage: 532480
- runDuration: 154.967s
- scanCount: 295393

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Attempt To Add Certificate To Untrusted Store :white_check_mark:
- diskUsage: 598016
- runDuration: 6.627s
- scanCount: 6565

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Attempted Credential Dump From Registry via Reg exe :white_check_mark:
- diskUsage: 651264
- runDuration: 7.514s
- scanCount: 7007

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Batch File Write to System32 :white_check_mark:
- diskUsage: 978944
- runDuration: 4.0600000000000005s
- scanCount: 504

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

BITS Job Persistence :white_check_mark:
- diskUsage: 536576
- runDuration: 3.846s
- scanCount: 3017

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

BITSAdmin Download File :white_check_mark:
- diskUsage: 499712
- runDuration: 4.659s
- scanCount: 3017

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Create local admin accounts using net exe :white_check_mark:
- diskUsage: 618496
- runDuration: 6.349s
- scanCount: 6394

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Create or delete windows shares using net exe :white_check_mark:
- diskUsage: 516096
- runDuration: 5.479s
- scanCount: 6592

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Creation of Shadow Copy with wmic and powershell :white_check_mark:
- diskUsage: 536576
- runDuration: 6.4110000000000005s
- scanCount: 7013

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Credential Dumping via Copy Command from Shadow Copy :white_check_mark:
- diskUsage: 397312
- runDuration: 6.273s
- scanCount: 7013

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Credential Dumping via Symlink to Shadow Copy :white_check_mark:
- diskUsage: 507904
- runDuration: 5.891s
- scanCount: 7013

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect PsExec With accepteula Flag :x:
- diskUsage: 499712
- runDuration: 5.344s
- scanCount: 6156

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Domain Account Discovery With Net App :white_check_mark:
- diskUsage: 614400
- runDuration: 6.035s
- scanCount: 7259

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect PsExec With accepteula Flag :white_check_mark:
- diskUsage: 503808
- runDuration: 2.89s
- scanCount: 13

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Dump LSASS via procdump :white_check_mark:
- diskUsage: 618496
- runDuration: 6.66s
- scanCount: 7963

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Extract SAM from Registry :white_check_mark:
- diskUsage: 520192
- runDuration: 6.646s
- scanCount: 7007

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Extract SAM from Registry :white_check_mark:
- diskUsage: 520192
- runDuration: 6.345s
- scanCount: 7007

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Processes created by netsh :white_check_mark:
- diskUsage: 507904
- runDuration: 9.4s
- scanCount: 14187

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Extraction of Registry Hives :white_check_mark:
- diskUsage: 524288
- runDuration: 6.172s
- scanCount: 7007

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

SearchProtocolHost with no Command Line with Network :x:
- diskUsage: 753664
- runDuration: 3.6870000000000003s
- scanCount: 1032

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Regasm with no Command Line Arguments :white_check_mark:
- diskUsage: 499712
- runDuration: 4.664s
- scanCount: 4460

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect regsvcs with no Command Line Arguments :white_check_mark:
- diskUsage: 499712
- runDuration: 6.444s
- scanCount: 4460

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious DLLHost no Command Line Arguments :white_check_mark:
- diskUsage: 499712
- runDuration: 55.548s
- scanCount: 104295

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious GPUpdate no Command Line Arguments :white_check_mark:
- diskUsage: 499712
- runDuration: 56.248000000000005s
- scanCount: 104295

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious Rundll32 with no Command Line Arguments :white_check_mark:
- diskUsage: 499712
- runDuration: 9.378s
- scanCount: 13366

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious SearchProtocolHost no Command Line Arguments :white_check_mark:
- diskUsage: 495616
- runDuration: 55.594s
- scanCount: 104295

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Office Document Spawned Child Process To Download :white_check_mark:
- diskUsage: 544768
- runDuration: 13.835s
- scanCount: 22352

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Renamed PSExec :white_check_mark:
- diskUsage: 512000
- runDuration: 6.678s
- scanCount: 8239

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Renamed 7-Zip :white_check_mark:
- diskUsage: 606208
- runDuration: 10.691s
- scanCount: 17329

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Renamed RClone :white_check_mark:
- diskUsage: 606208
- runDuration: 4.852s
- scanCount: 5913

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Winword Spawning Cmd :white_check_mark:
- diskUsage: 512000
- runDuration: 17.528s
- scanCount: 31087

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Winword Spawning PowerShell :white_check_mark:
- diskUsage: 536576
- runDuration: 17.647000000000002s
- scanCount: 31087

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows Event Log Cleared :x:
- diskUsage: 155648
- runDuration: 1.103s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Wermgr Process Spawned CMD Or Powershell Process :white_check_mark:
- diskUsage: 557056
- runDuration: 157.269s
- scanCount: 295393

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

W3WP Spawning Shell :white_check_mark:
- diskUsage: 548864
- runDuration: 29.301000000000002s
- scanCount: 49891

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Wermgr Process Create Executable File :x:
- diskUsage: 937984
- runDuration: 221.77s
- scanCount: 295393

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Renamed rundll32.exe Rename :white_check_mark:
- diskUsage: 507904
- runDuration: 9.041s
- scanCount: 13366

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious Rundll32 dllregisterserver :white_check_mark:
- diskUsage: 503808
- runDuration: 9.315s
- scanCount: 13366

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect regsvr32 Registering DLLs from non-standard paths :white_check_mark:
- diskUsage: 524288
- runDuration: 4.619s
- scanCount: 3317

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious Rundll32 PluginInit :white_check_mark:
- diskUsage: 503808
- runDuration: 52.182s
- scanCount: 98068

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

RunDLL Loading DLL By Ordinal :white_check_mark:
- diskUsage: 507904
- runDuration: 9.374s
- scanCount: 13366

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Remote WMI Command Attempt :white_check_mark:
- diskUsage: 499712
- runDuration: 5.7940000000000005s
- scanCount: 6574

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Remote Process Instantiation via WMI :white_check_mark:
- diskUsage: 614400
- runDuration: 5.655s
- scanCount: 6575

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Recursive Delete of Directory In Batch CMD :white_check_mark:
- diskUsage: 614400
- runDuration: 2.552s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Process Kill Base On File Path :white_check_mark:
- diskUsage: 516096
- runDuration: 134.89600000000002s
- scanCount: 271717

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Office Product Spawning CertUtil :white_check_mark:
- diskUsage: 528384
- runDuration: 4.281s
- scanCount: 4596

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Office Product Spawning Wmic :white_check_mark:
- diskUsage: 528384
- runDuration: 4.4510000000000005s
- scanCount: 4596

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

PowerShell Start-BitsTransfer :white_check_mark:
- diskUsage: 626688
- runDuration: 3.7030000000000003s
- scanCount: 3019

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Office Product Spawning Rundll32 with no DLL :white_check_mark:
- diskUsage: 528384
- runDuration: 3.936s
- scanCount: 3672

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Office Product Spawning BITSAdmin :white_check_mark:
- diskUsage: 528384
- runDuration: 4.587s
- scanCount: 4596

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Mshta spawning Rundll32 OR Regsvr32 Process :white_check_mark:
- diskUsage: 520192
- runDuration: 10.299s
- scanCount: 15578

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Office Product Spawn CMD Process :white_check_mark:
- diskUsage: 520192
- runDuration: 10.079s
- scanCount: 15578

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Nishang PowershellTCPOneLine :white_check_mark:
- diskUsage: 409600
- runDuration: 13.765s
- scanCount: 21930

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Office Application Spawn rundll32 process :white_check_mark:
- diskUsage: 524288
- runDuration: 33.092s
- scanCount: 58627

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Office Application Spawn Regsvr32 process :white_check_mark:
- diskUsage: 532480
- runDuration: 27.949s
- scanCount: 51146

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Powershell Disable Security Monitoring :white_check_mark:
- diskUsage: 671744
- runDuration: 8.038s
- scanCount: 10934

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Excessive Usage Of Net App :white_check_mark:
- diskUsage: 520192
- runDuration: 137.308s
- scanCount: 271717

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Office Product Spawning MSHTA :white_check_mark:
- diskUsage: 528384
- runDuration: 4.484s
- scanCount: 4596

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Excessive Service Stop Attempt :white_check_mark:
- diskUsage: 528384
- runDuration: 135.862s
- scanCount: 271717

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

CertUtil With Decode Argument :white_check_mark:
- diskUsage: 499712
- runDuration: 2.958s
- scanCount: 1766

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Batch File Write to System32 :white_check_mark:
- diskUsage: 978944
- runDuration: 3.787s
- scanCount: 504

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Attempt To Stop Security Service :white_check_mark:
- diskUsage: 614400
- runDuration: 6.034s
- scanCount: 7345

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

CertUtil Download With VerifyCtl and Split Arguments :white_check_mark:
- diskUsage: 507904
- runDuration: 3.398s
- scanCount: 2291

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Any Powershell DownloadString :white_check_mark:
- diskUsage: 622592
- runDuration: 13.648s
- scanCount: 21931

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Allow File And Printing Sharing In Firewall :white_check_mark:
- diskUsage: 389120
- runDuration: 4.587s
- scanCount: 4627

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Any Powershell DownloadFile :white_check_mark:
- diskUsage: 528384
- runDuration: 14.387s
- scanCount: 21929

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Allow Network Discovery In Firewall :white_check_mark:
- diskUsage: 397312
- runDuration: 5.113s
- scanCount: 4628

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

CertUtil Download With URLCache and Split Arguments :white_check_mark:
- diskUsage: 507904
- runDuration: 3.279s
- scanCount: 2291

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Malicious PowerShell Process - Connect To Internet With Hidden Window :white_check_mark:
- diskUsage: 651264
- runDuration: 11.579s
- scanCount: 17751

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Malicious PowerShell Process - Encoded Command :white_check_mark:
- diskUsage: 626688
- runDuration: 5.392s
- scanCount: 6238

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Malicious PowerShell Process - Execution Policy Bypass :white_check_mark:
- diskUsage: 630784
- runDuration: 3.228s
- scanCount: 1188

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Malicious PowerShell Process With Obfuscation Techniques :white_check_mark:
- diskUsage: 548864
- runDuration: 17.931s
- scanCount: 29946

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
