### PR TITLE
linux_persist_priv_batch_2

### PR DESCRIPTION
**Pull request by tccontre**
### File Creation In Init Directory, File Creation In Profile Directory, Creation of Services (Start, Restart and Systemd Timer), SUID Enabling 
linux_file_creation_in_init_boot_directory.yml (passed)
linux_file_creation_in_profile_directory.yml (passed)
linux_service_file_created_in_systemd_directory.yml (passed)
linux_service_restarted.yml (passed)
linux_service_started_or_enabled.yml (passed)
linux_setuid_using_chmod_utility.yml (passed)
linux_setuid_using_setcap_utility.yml (passed)

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Setuid Using Setcap Utility :x:
- diskUsage: 
- runDuration: s
- scanCount:

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Setuid Using Setcap Utility :x:
- diskUsage: 
- runDuration: s
- scanCount:

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Setuid Using Setcap Utility :white_check_mark:
- diskUsage: 393216
- runDuration: 4.968s
- scanCount: 4562

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Service Started Or Enabled :white_check_mark:
- diskUsage: 495616
- runDuration: 6.6850000000000005s
- scanCount: 8093

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Service File Created In Systemd Directory :white_check_mark:
- diskUsage: 614400
- runDuration: 30.978s
- scanCount: 58175

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux File Creation In Profile Directory :white_check_mark:
- diskUsage: 475136
- runDuration: 23.830000000000002s
- scanCount: 41839

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux File Creation In Init Boot Directory :x:
- diskUsage: 438272
- runDuration: 23.525000000000002s
- scanCount: 41839

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux File Creation In Init Boot Directory :x:
- diskUsage: 471040
- runDuration: 23.848s
- scanCount: 41839

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux File Creation In Init Boot Directory :white_check_mark:
- diskUsage: 499712
- runDuration: 24.176000000000002s
- scanCount: 41839

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Service Restarted :white_check_mark:
- diskUsage: 475136
- runDuration: 6.192s
- scanCount: 8093

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Setuid Using Chmod Utility :white_check_mark:
- diskUsage: 376832
- runDuration: 4.4190000000000005s
- scanCount: 3617

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
