### PR TITLE
Detection Testing Part 2

### PR DESCRIPTION
**Pull request by P4T12ICK**
WIP

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Script Execution via WMI :white_check_mark:
- diskUsage: 356352
- runDuration: 7.7860000000000005s
- scanCount: 11187

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Schtasks used for forcing a reboot :x:
- diskUsage: 417792
- runDuration: 1.164s
- scanCount: 39

**Review by patel-bhavin — DISMISSED** [review]

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Schtasks used for forcing a reboot :white_check_mark:
- diskUsage: 434176
- runDuration: 1.122s
- scanCount: 38

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Shim Database File Creation :white_check_mark:
- diskUsage: 258048
- runDuration: 0.622s
- scanCount: 9

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Single Letter Process On Endpoint :white_check_mark:
- diskUsage: 348160
- runDuration: 1.115s
- scanCount: 93

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious File Write :white_check_mark:
- diskUsage: 360448
- runDuration: 4.897s
- scanCount: 5972

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious writes to windows Recycle Bin :white_check_mark:
- diskUsage: 524288
- runDuration: 1.713s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

System Processes Run From Unexpected Locations :white_check_mark:
- diskUsage: 368640
- runDuration: 4.985s
- scanCount: 6703

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Unusually Long Command Line :white_check_mark:
- diskUsage: 352256
- runDuration: 5.121s
- scanCount: 6703

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

USN Journal Deletion :white_check_mark:
- diskUsage: 352256
- runDuration: 4.606s
- scanCount: 5952

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

WMI Permanent Event Subscription - Sysmon :white_check_mark:
- diskUsage: 110592
- runDuration: 1.211s
- scanCount: 1117

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious LNK file launching a process :white_check_mark:
- diskUsage: 569344
- runDuration: 6.699s
- scanCount: 7

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Attempt To Set Default PowerShell Execution Policy To Unrestricted or Bypass :white_check_mark:
- diskUsage: 266240
- runDuration: 5.087s
- scanCount: 7665

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Create or delete windows shares using net exe :white_check_mark:
- diskUsage: 360448
- runDuration: 4.862s
- scanCount: 6334

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

First Time Seen Running Windows Service :x:
- diskUsage: 98304
- runDuration: 0.296s
- scanCount: 649

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

First Time Seen Running Windows Service :x:
- diskUsage: 98304
- runDuration: 0.317s
- scanCount: 649

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

First Time Seen Running Windows Service :x:
- diskUsage: 98304
- runDuration: 0.274s
- scanCount: 649

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
