### PR TITLE
Cloud data exfil detections

### PR DESCRIPTION
**Pull request by P4T12ICK**

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

O365 Suspicious User Email Forwarding :white_check_mark:
- diskUsage: 131072
- runDuration: 0.876s
- scanCount: 77

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

O365 Suspicious Admin Email Forwarding :white_check_mark:
- diskUsage: 131072
- runDuration: 0.8320000000000001s
- scanCount: 77

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

O365 PST export alert :white_check_mark:
- diskUsage: 122880
- runDuration: 0.9580000000000001s
- scanCount: 14

**Review by tccontre — APPROVED** [review]
lgtm

**Pull request merged**
