### PR TITLE
crowdstrike_oauth_api_playbook_v2

### PR DESCRIPTION
**Pull request by tccontre**
### Details
- [ ] modified:   playbooks/CrowdStrike_OAuth_API_Dynamic_Analysis.json
- [ ] modified:   playbooks/CrowdStrike_OAuth_API_Dynamic_Analysis.png
- [ ] modified:   playbooks/CrowdStrike_OAuth_API_Dynamic_Analysis.py

_What does this PR have in it? Screenshots are worth 1000 words 😄_

minimized the block used.

Screenshot 2023-03-30 at 11 33 32

### Checklist

- [ ] Validate name matches `<platform>_<mitre att&ck technique>_<short description>` nomenclature
- [ ] [CI/CD](https://github.com/splunk/security_content/actions) jobs passed ✔️ 
- [ ] Validated SPL logic.
- [ ] Validated tags, description, and how to implement.
- [ ] Verified references match analytic.

### CODE REVIEW

**Comment by P4T12ICK** [comment]
# Pull Request Type

##### Please check all that apply:
- [x] New playbook
- [ ] Bugfix
- [ ] Feature add
- [ ] Code style update (formatting, renaming)
- [ ] Documentation
- [ ] Other (please describe): 

# Release Notes
Replace the following list with release notes that describe the high level components of the PR:
- Feature - Added new playbook for reputation checks
- Bug - Fixed python logic for a custom code block
- etc. etc.

# Playbook quality checklist
Please check if your PR fulfills the following requirements.

### Requirements for Settings

- [x] Playbook name is A-Z in Title case with underscores between words. (e.g. MS_Graph_Search_and_Purge)
- [x] Category in Title case with spaces between words (e.g. Identifier Reputation Analysis)
- [x] Description is free of grammatical errors and describe what the playbook does.
- [x] Notes list any setup required on the third-party API as well as intended areas for customization.
- [x] Label is set to '\*'
    
### Requirements for all playbooks

- [x] Playbook block count not greater than 15 (not including Start and End blocks).
- [x] No more than 3 branching paths.
- [x] If referencing a custom list, Notes document what the expected values are in that custom list.

### Requirements for all playbook blocks

- [x] All blocks have a custom name no more than 4 words, all lowercase, and separated by space (e.g. close workbook task)
- [x] All blocks that support a Notes Tooltip have it filled out. Must be grammatically correct and describes the intended purpose of that block.
- [x] Where custom code is used, block notes indicate presence of custom code (e.g. "This block uses custom code")
- [x] No block is disabled by custom code
- [x] Custom code is documented with notes

### Requirements for specific blocks

##### Action

- [x] Use apps available on Splunkbase
- [x] Use asset names that are the app name, all lowercase separated by underscores (e.g. Azure AD Graph becomes azure_ad_graph)

##### Utility 

- [x] Block is using community version

##### Playbook

- [x] Block is using local version

### Requirements for specific playbooks

##### Input playbooks
- [x] Start blocks use ocsf variable names and a minimum of one data type per variable name (e.g. device (type: host name))
- [x] Has at least one category tag (e.g. reputation)
- [x] Playbook has a tag for each vendor app used

# Other considerations (PR type specific)
- [x] If new playbook, there is a screenshot ending in .png with the same name as the playbook .json
- [x] Playbook major minor version matches repo (e.g. 5.5 != 6.0)
- [x] PR contains both .py and .json

---
Thanks for contributing!

**Review by P4T12ICK — CHANGES_REQUESTED** [review]
- the generated report should be part of the end block as output

**Review by P4T12ICK — CHANGES_REQUESTED** [review]
- [x] list demux block need a description and notes.

**Comment by P4T12ICK** [comment]
looks good to me

**Comment by kelby-shelton** [comment]
Issues:
1. Rename block `crowdstrike url detonation` to `url detonation`
2. Add an option to the filter to only proceed if status is success and message doesn't contain "Timed out while waiting for the result"
3. `list_demux` is missing a Tooltip
4. Normalize score blocks are not normalizing it to the score and score_id as listed here: https://schema.ocsf.io/objects/reputation
5. Normalize file reputation has a debug statement uncommented
6. Playbook tags list `domain` and `ip` but those values aren't supported by the playbook

**Comment by tccontre** [comment]
> Issues:
> 
> 1. Rename block `crowdstrike url detonation` to `url detonation`
> 2. Add an option to the filter to only proceed if status is success and message doesn't contain "Timed out while waiting for the result"
> 3. `list_demux` is missing a Tooltip
> 4. Normalize score blocks are not normalizing it to the score and score_id as listed here: https://schema.ocsf.io/objects/reputation
> 5. Normalize file reputation has a debug statement uncommented
> 6. Playbook tags list `domain` and `ip` but those values aren't supported by the playbook

-- updated! all issue was fixed.

**Review by P4T12ICK — APPROVED** [review]

**Pull request merged**
