### PR TITLE
detection testing branch

### PR DESCRIPTION
**Pull request by P4T12ICK**
detection testing branch

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Abnormally High Number of Cloud Instances Launched :x:
- diskUsage: 163840
- runDuration: 0.003s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Abnormally High Number Of Cloud Instances Destroyed :x:
- diskUsage: 163840
- runDuration: 0.003s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Abnormally High Number Of Cloud Infrastructure API Calls :white_check_mark:
- diskUsage: 368640
- runDuration: 9.38s
- scanCount: 8102

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

AWS Detect Users creating keys with encrypt policy without MFA :white_check_mark:
- diskUsage: 143360
- runDuration: 0.5660000000000001s
- scanCount: 19

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

AWS Detect Users with KMS keys performing encryption S3 :white_check_mark:
- diskUsage: 131072
- runDuration: 0.555s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

AWS Network Access Control List Deleted :white_check_mark:
- diskUsage: 118784
- runDuration: 0.5640000000000001s
- scanCount: 4

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

AWS Network Access Control List Created with All Open Ports :white_check_mark:
- diskUsage: 180224
- runDuration: 0.911s
- scanCount: 10

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect New Open S3 buckets :white_check_mark:
- diskUsage: 147456
- runDuration: 0.587s
- scanCount: 9

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect New Open S3 Buckets over AWS CLI :white_check_mark:
- diskUsage: 143360
- runDuration: 0.606s
- scanCount: 9

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

High Number of Login Failures from a single source :x:
- diskUsage: 126976
- runDuration: 0.524s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect IPv6 Network Infrastructure Threats :x:
- diskUsage: 106496
- runDuration: 0.229s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect hosts connecting to dynamic domain providers :white_check_mark:
- diskUsage: 212992
- runDuration: 1.545s
- scanCount: 679

**Review by jzsplunk — APPROVED** [review]
LGTM.  Thank you for adding the additional logic to generate.py

**Pull request merged**
