### PR TITLE
Multiple Updates

### PR DESCRIPTION
**Pull request by TheLawsOfChaos**
### Details

Update powershell_fileless_script_contains_base64_encoded_content.yml
Renamed risk object ComputerName to Computer
Removed User from risk object (UserID is the proper field, but the SID isn't part of assets/identities, so just full on removed the part of the stanza for User)
Removes the 's' off EventCodes

Update powershell_fileless_script_contains_base64_encoded_content.yml
Updated risk message to the new field names.

Update windows_service_created_with_suspicious_service_path.yml
Updated field names to match, and added dest and user_id to the query for investigation purposes.

Update create_local_admin_accounts_using_net_exe.yml
Added parent_process_name into the query, as the rest of the yaml wanted it.

Update delete_shadowcopy_with_powershell.yml
Observable User was changed to UserID. I don't think this is useful as it's the SID, and not sure if all folks will capture SID for the assets & identities, so maybe deleting the part of the stanza for the Victim User is better.

### Checklist

- [ ] Validate name matches `<platform>_<mitre att&ck technique>_<short description>` nomenclature
- [ ] [CI/CD](https://github.com/splunk/security_content/actions) jobs passed ✔️ 
- [ ] Validated SPL logic.
- [ ] Validated tags, description, and how to implement.
- [ ] Verified references match analytic.

### CODE REVIEW

**Comment by patel-bhavin** [comment]
thank you so much for this PR, i have updated your searches here to testing them via detection testing!
https://github.com/splunk/security_content/pull/2535

**Comment by patel-bhavin** [comment]
@TheLawsOfChaos : Reopening the PR and getting this merged to get your that contribution credit on Git. For that I created a duplicate PR to test(https://github.com/splunk/security_content/pull/2535/files) and looks like there is an error with this search ->

 `windows_service_created_with_suspicious_service_path.yml`

Please check this new SPL and update it in this current PR and we can get this merged!
image

**Comment by TheLawsOfChaos** [comment]
@patel-bhavin updated the .yml, sorry about that!

**Comment by patel-bhavin** [comment]
hello @TheLawsOfChaos : your current PR still shows that detection using ImagePath- which doesnt match the screenshot in the above comment. Did your change get pushed?

This is the screenshot from this PR in which detection using ImagePath 
**
image
**

**Comment by patel-bhavin** [comment]
all the detections are tested and validated in https://github.com/splunk/security_content/pull/2535

**Review by patel-bhavin — APPROVED** [review]

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
