### PR TITLE
Unusual Volume of Data Download from Internal Server Per Entity

### PR DESCRIPTION
**Pull request by xlinsplunk**

### CODE REVIEW

**Comment by xlinsplunk** [comment]
Attach a screenshot to illustrate all the fields used in the detection are available from BA pulsar source.
Screen Shot 2022-02-09 at 3 53 18 PM

Screen Shot 2022-02-09 at 11 49 06 AM

**Comment by josehelps** [comment]
needs to be in experimental

**Comment by xlinsplunk** [comment]
moved detection to experimental, with updated data link to attack_range

**Comment by xlinsplunk** [comment]
close this PR for it was merged in another PR: https://github.com/splunk/security_content/pull/2009/files

**Pull request closed without merging**
