### PR TITLE
Double The Haag's

### PR DESCRIPTION
**Pull request by MHaggis**
## New Analytic Story
- Masquerading - Rename System Utilities
## New Detections
- Anomalous Usage of 7z (Passed)
- Office Product Spawning MSHTA (Passed)
- Office Product Spawning Wmic (Passed)
- Office Product Spawning BITSAdmin (Passed)
- Office Product Spawning CertUtil (Passed)

## Updated Detections
- System Processes Run From Unexpected Locations

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Anomalous usage of 7zip :x:
- diskUsage: 393216
- runDuration: 0.997s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Anomalous usage of 7zip :white_check_mark:
- diskUsage: 413696
- runDuration: 5.333s
- scanCount: 8014

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Office Product Spawning CertUtil :white_check_mark:
- diskUsage: 425984
- runDuration: 3.481s
- scanCount: 4337

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Office Product Spawning Wmic :white_check_mark:
- diskUsage: 425984
- runDuration: 3.902s
- scanCount: 4337

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Office Product Spawning BITSAdmin :white_check_mark:
- diskUsage: 425984
- runDuration: 3.754s
- scanCount: 4337

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Office Product Spawning MSHTA :white_check_mark:
- diskUsage: 425984
- runDuration: 3.954s
- scanCount: 4337

**Review by tccontre — APPROVED** [review]
looks good to me!

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
