### PR TITLE
Update new attack data project

### PR DESCRIPTION
**Pull request by P4T12ICK**
- Update url links for attack data to new Attack Data project using Git LFS
- Update Detection Testing Service

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Samsam Test File Write :white_check_mark:
- diskUsage: 253952
- runDuration: 0.624s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Sc exe Manipulating Windows Services :white_check_mark:
- diskUsage: 434176
- runDuration: 1.177s
- scanCount: 8

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Scheduled Task Name Used by Dragonfly Threat Actors :white_check_mark:
- diskUsage: 352256
- runDuration: 4.66s
- scanCount: 6026

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Script Execution via WMI :x:
- diskUsage: 344064
- runDuration: 0.989s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Schtasks used for forcing a reboot :x:
- diskUsage: 430080
- runDuration: 1.1340000000000001s
- scanCount: 40

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Script Execution via WMI :x:
- diskUsage: 352256
- runDuration: 4.072s
- scanCount: 4949

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Schtasks scheduling job on remote system :white_check_mark:
- diskUsage: 434176
- runDuration: 1.189s
- scanCount: 94

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Script Execution via WMI :x:
- diskUsage: 344064
- runDuration: 3.991s
- scanCount: 4949

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
