### PR TITLE
Darkside Ransomware

### PR DESCRIPTION
**Pull request by patel-bhavin**
## New Detections
- Delete ShadowCopy With PowerShell (Experimental)
- Extract SAM from Registry (Passed)
- SLUI RunAs Elevated (Passed)
- SLUI Spawning a Process (Passed)
- Detect Renamed RClone (Passed)
- Detect RClone Command-Line Usage (Passed)
-  CMLUA Or CMSTPLUA UAC Bypass (Passed)

## New Analytic Story
- DarkSide Ransomware

## Updated Detections
- Ransomware Notes bulk creation
- Cobalt Strike Named Pipes

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Delete ShadowCopy With PowerShell :x:
- diskUsage: 159744
- runDuration: 0.869s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Delete ShadowCopy With PowerShell :x:
- diskUsage: 159744
- runDuration: 0.789s
- scanCount: 275

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

CMLUA Or CMSTPLUA UAC Bypass :white_check_mark:
- diskUsage: 299008
- runDuration: 0.8240000000000001s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Delete ShadowCopy With PowerShell :x:
- diskUsage: 163840
- runDuration: 0.776s
- scanCount: 275

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

CMLUA Or CMSTPLUA UAC Bypass :white_check_mark:
- diskUsage: 143360
- runDuration: 1.043s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect RClone Command-Line Usage :white_check_mark:
- diskUsage: 438272
- runDuration: 5.822s
- scanCount: 5653

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Renamed RClone :white_check_mark:
- diskUsage: 143360
- runDuration: 0.856s
- scanCount: 61

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Extract SAM from Registry :white_check_mark:
- diskUsage: 417792
- runDuration: 5.305s
- scanCount: 6748

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

SLUI RunAs Elevated :x:
- diskUsage: 495616
- runDuration: 1.415s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

SLUI Spawning a Process :x:
- diskUsage: 94208
- runDuration: 0.003s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

SLUI Spawning a Process :white_check_mark:
- diskUsage: 409600
- runDuration: 8.276s
- scanCount: 13801

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

SLUI RunAs Elevated :white_check_mark:
- diskUsage: 499712
- runDuration: 1.5190000000000001s
- scanCount: 4

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Delete ShadowCopy With PowerShell :x:
- diskUsage: 163840
- runDuration: 1.184s
- scanCount: 275

**Review by MHaggis — APPROVED** [review]

**Pull request merged**
