### PR TITLE
new detection

### PR DESCRIPTION
**Pull request by P4T12ICK**
Kubernetes detections

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Kubernetes Nginx Ingress LFI :x:
- diskUsage: 172032
- runDuration: 0.889s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Kubernetes Nginx Ingress LFI :x:
- diskUsage: 172032
- runDuration: 1.063s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Kubernetes Nginx Ingress LFI :white_check_mark:
- diskUsage: 180224
- runDuration: 1.5210000000000001s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Kubernetes Nginx Ingress LFI :x:
- diskUsage: 172032
- runDuration: 0.9430000000000001s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Kubernetes Nginx Ingress LFI :white_check_mark:
- diskUsage: 180224
- runDuration: 1.347s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Kubernetes Nginx Ingress RFI :x:
- diskUsage: 172032
- runDuration: 0.8150000000000001s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Kubernetes Nginx Ingress RFI :white_check_mark:
- diskUsage: 180224
- runDuration: 0.881s
- scanCount: 4

**Review by tccontre — DISMISSED** [review]

**Review by tccontre — DISMISSED** [review]

**Review by tccontre — APPROVED** [review]

**Pull request merged**
