### PR TITLE
New test file format

### PR DESCRIPTION
**Pull request by P4T12ICK**
Changes:
- new test file format
- small changes to detection testing service

### CODE REVIEW

**Review by josehelps — CHANGES_REQUESTED** [review]
I am sure you didn't mean to commit `bin/tmp.py` 😉

**Comment by P4T12ICK** [comment]
yeah. I removed the tmp.py.

**Comment by P4T12ICK** [comment]
test

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Access LSASS Memory for Dump Creation :x:
- diskUsage: 122880
- runDuration: 3.931s
- scanCount: 6206

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Access LSASS Memory for Dump Creation :x:
- diskUsage: 122880
- runDuration: 2.677s
- scanCount: 3919

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Attempt To Add Certificate To Untrusted Store :white_check_mark:
- diskUsage: 466944
- runDuration: 1.024s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Attempted Credential Dump From Registry via Reg exe :white_check_mark:
- diskUsage: 520192
- runDuration: 8.432s
- scanCount: 19464

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Create local admin accounts using net exe :white_check_mark:
- diskUsage: 409600
- runDuration: 8.619s
- scanCount: 39867

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Access LSASS Memory for Dump Creation :x:
- diskUsage: 122880
- runDuration: 6.299s
- scanCount: 10132

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Create Remote Thread into LSASS :x:
- diskUsage: 118784
- runDuration: 0.545s
- scanCount: 95

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Access LSASS Memory for Dump Creation :x:
- diskUsage: 122880
- runDuration: 4.814s
- scanCount: 7684

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Creation of Shadow Copy with wmic and powershell :white_check_mark:
- diskUsage: 401408
- runDuration: 8.557s
- scanCount: 36023

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Credential Dumping via Copy Command from Shadow Copy :white_check_mark:
- diskUsage: 303104
- runDuration: 1.393s
- scanCount: 70

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Creation of Shadow Copy :white_check_mark:
- diskUsage: 430080
- runDuration: 8.86s
- scanCount: 31453

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Activity Related to Pass the Hash Attacks :x:
- diskUsage: 135168
- runDuration: 0.468s
- scanCount: 27

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Credential Dumping via Symlink to Shadow Copy :white_check_mark:
- diskUsage: 405504
- runDuration: 8.072000000000001s
- scanCount: 32559

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Credential Dumping through LSASS access :x:
- diskUsage: 118784
- runDuration: 0.546s
- scanCount: 118

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Path Interception By Creation Of program exe :white_check_mark:
- diskUsage: 409600
- runDuration: 8.702s
- scanCount: 35664

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Dump LSASS via comsvcs DLL :white_check_mark:
- diskUsage: 495616
- runDuration: 7.009s
- scanCount: 10353

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect New Local Admin account :x:
- diskUsage: 143360
- runDuration: 0.546s
- scanCount: 31

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Kerberoasting spn request with RC4 encryption :x:
- diskUsage: 110592
- runDuration: 0.429s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Malicious PowerShell Process - Encoded Command :white_check_mark:
- diskUsage: 499712
- runDuration: 1.452s
- scanCount: 2154

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious Reg exe Process :white_check_mark:
- diskUsage: 733184
- runDuration: 17.055s
- scanCount: 32397

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Schtasks scheduling job on remote system :white_check_mark:
- diskUsage: 471040
- runDuration: 1.5210000000000001s
- scanCount: 14490

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Short Lived Windows Accounts :white_check_mark:
- diskUsage: 360448
- runDuration: 4.793s
- scanCount: 22740

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Process execution via wmi :white_check_mark:
- diskUsage: 405504
- runDuration: 8.241s
- scanCount: 31672

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Unsigned Image Loaded by LSASS :x:
- diskUsage: 122880
- runDuration: 0.549s
- scanCount: 15

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

System Information Discovery Detection :white_check_mark:
- diskUsage: 409600
- runDuration: 8.117s
- scanCount: 32073

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Unload Sysmon Filter Driver :white_check_mark:
- diskUsage: 405504
- runDuration: 6.944s
- scanCount: 30067

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows Event Log Cleared :white_check_mark:
- diskUsage: 151552
- runDuration: 0.486s
- scanCount: 14

**Review by josehelps — APPROVED** [review]

**Pull request merged**
