### PR TITLE
WhisperGateIsOpen

### PR DESCRIPTION
**Pull request by tccontre**
### Minor Modification

- powershell_windows_defender_exclusion_commands.yml
- suspicious_process_file_path.yml
- windows_defender_exclusion_registry_entry.yml
- executables_or_script_creation_in_suspicious_path.yml
- add_or_set_windows_defender_exclusion.yml
- attempt_to_stop_security_service.yml
- wscript_or_cscript_suspicious_child_process.yml  
- process_deleting_its_process_file_path.yml
- high_file_deletion_frequency.yml

### Analytic story WhisperGate
stories/whispergate.yml

### process macro
- process_ping.yml

### new detection

- suspicious_process_with_discord_dns_query.yml (passed)
- ping_sleep_batch_command.yml (passed)
- powershell_remove_windows_defender_directory.yml (passed)
- excessive_file_deletion_in_windefender_folder.yml (passed)

### docker detection test ( all passed)

Screenshot 2022-01-24 at 11 20 48

### CODE REVIEW

**Comment by MHaggis** [comment]
Added source

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious Process With Discord DNS Query :white_check_mark:
- diskUsage: 303104
- runDuration: 3.094s
- scanCount: 2367

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Powershell Remove Windows Defender Directory :white_check_mark:
- diskUsage: 172032
- runDuration: 1.425s
- scanCount: 97

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Ping Sleep Batch Command :white_check_mark:
- diskUsage: 552960
- runDuration: 4.025s
- scanCount: 4

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Excessive File Deletion In WinDefender Folder :white_check_mark:
- diskUsage: 184320
- runDuration: 2.293s
- scanCount: 1981

**Review by MHaggis — APPROVED** [review]

**Pull request merged**
