### PR TITLE
The Haag at The Gates

### PR DESCRIPTION
**Pull request by MHaggis**
## New Analytics
- Microsoft Exchange Mailbox Replication service writing Active Server Pages (Experimental)
- Windows DISM Remove Defender (Passed)
- Windows Raccine Scheduled Task Deletion (Passed)
- MSI Module Loaded by Non-System Binary (Passing with data, but not via batch due to events being jammed into 1 event)

image

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows DISM Remove Defender :white_check_mark:
- diskUsage: 376832
- runDuration: 2.935s
- scanCount: 6

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

MSI Module Loaded by Non-System Binary :x:
- diskUsage: 176128
- runDuration: 1.5070000000000001s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

MSI Module Loaded by Non-System Binary :x:
- diskUsage: 176128
- runDuration: 1.268s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows Raccine Scheduled Task Deletion :x:
- diskUsage: 421888
- runDuration: 2.404s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows Raccine Scheduled Task Deletion :x:
- diskUsage: 421888
- runDuration: 1.9080000000000001s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows Raccine Scheduled Task Deletion :white_check_mark:
- diskUsage: 425984
- runDuration: 3.169s
- scanCount: 2041

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

MSI Module Loaded by Non-System Binary :x:
- diskUsage: 180224
- runDuration: 1.304s
- scanCount: 1

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
