### PR TITLE
Tr162

### PR DESCRIPTION
**Pull request by xlinsplunk**
migrate two lateral movement to SPL2 ML first-seen algo.

### CODE REVIEW

**Comment by josehelps** [comment]
@xlinsplunk can you change the name of the search to exclude the MITRE technique ID, also lets have a SMLE notebook built that generates the data or includes the data to test this detection on SSA. Similar to that of the previous ones.

**Review by josehelps — CHANGES_REQUESTED** [review]
update detection name to exclude MITRE technique, also requires smle notebook for unit_testing

**Comment by xlinsplunk** [comment]
Hi Jose, all comments were addressed. Please review again. Thanks!

**Review by xlinsplunk — COMMENTED** [review]
done

**Review by xlinsplunk — COMMENTED** [review]
done

**Review by xlinsplunk — COMMENTED** [review]
done

**Comment by ghoto** [comment]
bump. Since we integrated validation for SSA content detections, the PRs can't be merged until these are resolved.

```

**Comment by ghoto** [comment]
Since we added validation for SSA detections, this PR can't be merged because the tests are failing.

https://cd.splunkdev.com/security-analytics/security-content/-/jobs/9403783
```
Failed tests
=================
tests/endpoint/detect_kerberoasting__ssa.test.yml
tests/endpoint/detect_pass_hash__ssa.test.yml
Cleaning up file based variables
00:00
ERROR: Job failed: exit code 1
```

**Comment by xlinsplunk** [comment]
changed to use 'input_event' SSA fields and tests passed.

**Comment by ghoto** [comment]
LGTM though we need to check with SSA how they are going to parse 4769, 4768 events.

It seems to me that the testing files might not look like SSA parsed events considering how they parsed 4688.

**Comment by xlinsplunk** [comment]
@ghoto 
field names in the input files were changed to be consistent with https://attack-range-attack-data.s3-us-west-2.amazonaws.com/T1003.002/windows-security_ssa.log

**Comment by ghoto** [comment]
LGTM

**Comment by josehelps** [comment]
@xlinsplunk can you rename the files to have the prefix ssa___ instead of a suffix? otherwise this looks good.

**Comment by xlinsplunk** [comment]
@d1vious 
yes, changed to use ssa___ as prefix.

**Review by josehelps — APPROVED** [review]
looks great

**Pull request merged**
