### PR TITLE
revil

### PR DESCRIPTION
**Pull request by tccontre**
## Revil Ransomware new detections:

1. Revil Registry Entry (passed)
2. Revil Common Exec Parameter (passed)
3. Modification Of Wallpaper (passed)
4. Wbemprox COM Object Execution (passed)
5. Known Services Killed by Ransomware (passed)

## move existing pattern out of experimental.
Delete ShadowCopy With PowerShell (passed)

## Conti ransomware
Conti Common Exec parameter (passed)

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Delete ShadowCopy With PowerShell :white_check_mark:
- diskUsage: 163840
- runDuration: 1.215s
- scanCount: 10

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Revil Registry Entry :white_check_mark:
- diskUsage: 389120
- runDuration: 4.186s
- scanCount: 5681

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Revil Common Exec Parameter :white_check_mark:
- diskUsage: 524288
- runDuration: 1.75s
- scanCount: 4

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Modification Of Wallpaper :white_check_mark:
- diskUsage: 143360
- runDuration: 0.81s
- scanCount: 9

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Wbemprox COM Object Execution :white_check_mark:
- diskUsage: 143360
- runDuration: 0.884s
- scanCount: 171

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Known Services Killed by Ransomware :white_check_mark:
- diskUsage: 135168
- runDuration: 0.769s
- scanCount: 16

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Conti Common Exec parameter :white_check_mark:
- diskUsage: 299008
- runDuration: 2.07s
- scanCount: 5

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
