### PR TITLE
script that shows the coverage for ssa detections

### PR DESCRIPTION
**Pull request by ghoto**
```
Tested detections
=================
endpoint/first_time_seen_cmd_line___ssa.yml
endpoint/detect_dump_lsass_memory_using_comsvcs___ssa.yml
endpoint/attempted_credential_dump_from_registry_via_reg_exe___ssa.yml
endpoint/rare_parent_process_relationship_lolbas___ssa.yaml
endpoint/unusual_lolbas_in_short_period_of_time___ssa.yml
endpoint/unusually_long_command_line___ssa.yml
endpoint/prohibited_apps_spawning_cmdprompt___ssa.yml


Untested detections
===================
endpoint/system_process_running_unexpected_location___ssa.yml
endpoint/credential_extraction_getaddbaccount_from_dump_ssa.yml
endpoint/credential_extraction_ms_debuggers_kernel_peek.yml
endpoint/credential_extraction_fgdump_cachedump_s_option_ssa.yml
endpoint/credential_extraction_fgdump_cachedump_v_option_ssa.yml
endpoint/credential_extraction_lazagne_command_options_ssa.yml
endpoint/credential_extraction_ms_debuggers_z_option.yml
application/detect_phishing_content___ssa.yml
```

### CODE REVIEW

**Review by peter-cg — DISMISSED** [review]
Could add a type option since this logic probably also works for ESCU

**Comment by ghoto** [comment]
@peter-cg yes, I was thinking of it. I need to think a better way to show the results, because there are way too many detections.

**Comment by ghoto** [comment]
This is the tail of the output..

```
application/spectre_and_meltdown_vulnerable_systems.yml


Tested SSA detections
====================
endpoint/unusual_lolbas_in_short_period_of_time___ssa.yml
endpoint/prohibited_apps_spawning_cmdprompt___ssa.yml
endpoint/detect_dump_lsass_memory_using_comsvcs___ssa.yml
endpoint/unusually_long_command_line___ssa.yml
endpoint/first_time_seen_cmd_line___ssa.yml
endpoint/attempted_credential_dump_from_registry_via_reg_exe___ssa.yml
endpoint/rare_parent_process_relationship_lolbas___ssa.yaml


Untested SSA detections
======================
endpoint/system_process_running_unexpected_location___ssa.yml
endpoint/credential_extraction_getaddbaccount_from_dump_ssa.yml
endpoint/credential_extraction_ms_debuggers_kernel_peek.yml
endpoint/credential_extraction_fgdump_cachedump_s_option_ssa.yml
endpoint/credential_extraction_fgdump_cachedump_v_option_ssa.yml
endpoint/credential_extraction_lazagne_command_options_ssa.yml
endpoint/credential_extraction_ms_debuggers_z_option.yml
application/detect_phishing_content___ssa.yml

ESCU testing coverage: (23/234) 0.10
SSA testing coverage: (7/15) 0.47
Total testing coverage: (30/249) 0.12
```

**Review by peter-cg — APPROVED** [review]
Nice. If you like, you could sort the detections when you print them (`'\n'.join(sorted(tested[k]))`). The `set()` will give you random ordering of the tested detections and the `walk` probably gives you inode order or something for the untested ones.

**Review by josehelps — APPROVED** [review]

**Pull request merged**
