### PR TITLE
fix_issues

### PR DESCRIPTION
**Pull request by tccontre**
## minor changes

- modified:   detections/endpoint/office_application_spawn_rundll32_process.yml (minor change)
- renamed:    detections/endpoint/suspicious_icedid_regsvr32_cmdline.yml -> detections/endpoint/regsvr32_with_known_silent_switch_cmdline.yml (passed)

## improved 
- modified:   detections/endpoint/office_application_drop_executable.yml (fix join unwanted events detection) (passed)
- renamed: detections/endpoint/regsvr32_silent_param_dll_loading.yml -> detections/endpoint/regsvr32_silent_and_install_param_dll_loading.yml (passed)

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Regsvr32 Silent and Install Param Dll Loading :white_check_mark:
- diskUsage: 528384
- runDuration: 6.074s
- scanCount: 6697

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Regsvr32 with Known Silent Switch Cmdline :x:
- diskUsage: 606208
- runDuration: 56.358000000000004s
- scanCount: 98068

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Regsvr32 with Known Silent Switch Cmdline :x:
- diskUsage: 528384
- runDuration: 53.591s
- scanCount: 98068

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Office Application Drop Executable :white_check_mark:
- diskUsage: 983040
- runDuration: 31.345000000000002s
- scanCount: 28118

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Regsvr32 with Known Silent Switch Cmdline :white_check_mark:
- diskUsage: 610304
- runDuration: 57.120000000000005s
- scanCount: 98255

**Review by patel-bhavin — DISMISSED** [review]

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Regsvr32 with Known Silent Switch Cmdline :white_check_mark:
- diskUsage: 507904
- runDuration: 53.632s
- scanCount: 98068

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Regsvr32 Silent and Install Param Dll Loading :white_check_mark:
- diskUsage: 606208
- runDuration: 5.4430000000000005s
- scanCount: 6737

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
