### PR TITLE
AWS_IAM_Account_Locking_Playbook

### PR DESCRIPTION
**Pull request by tccontre**
# Pull Request Type

https://github.com/splunk/security_content/assets/26181693/9e221b6c-141d-4ba5-93bb-945680dfedfb

##### Please check all that apply:
- [x] New playbook
- [ ] Bugfix
- [ ] Feature add
- [ ] Code style update (formatting, renaming)
- [ ] Documentation
- [ ] Other (please describe): 

# Release Notes
Replace the following list with release notes that describe the high level components of the PR:
- Feature - Added new playbook for reputation checks
- Bug - Fixed python logic for a custom code block
- etc. etc.

# Playbook quality checklist
Please check if your PR fulfills the following requirements.

### Requirements for Settings

- [x] Playbook name is A-Z in Title case with underscores between words. (e.g. MS_Graph_Search_and_Purge)
- [x] Category in Title case with spaces between words (e.g. Identifier Reputation Analysis)
- [x] Description is free of grammatical errors and describe what the playbook does.
- [x] Notes list any setup required on the third-party API as well as intended areas for customization.
- [x] Label is set to '\*'
    
### Requirements for all playbooks

- [x] Playbook block count not greater than 15 (not including Start and End blocks).
- [x] No more than 3 branching paths.
- [x] If referencing a custom list, Notes document what the expected values are in that custom list.

### Requirements for all playbook blocks

- [x] All blocks have a custom name no more than 4 words, all lowercase, and separated by space (e.g. close workbook task)
- [x] All blocks that support a Notes Tooltip have it filled out. Must be grammatically correct and describes the intended purpose of that block.
- [x] Where custom code is used, block notes indicate presence of custom code (e.g. "This block uses custom code")
- [x] No block is disabled by custom code
- [x] Custom code is documented with notes

##### Action

- [x] Use apps available on Splunkbase
- [x] Use asset names that are the app name, all lowercase separated by underscores (e.g. Azure AD Graph becomes azure_ad_graph)

##### Utility 

- [x] Block is using community version

##### Playbook

- [x] Block is using local version

##### Input playbooks
- [x] Start blocks use ocsf variable names and a minimum of one data type per variable name (e.g. device (type: host name))
- [x] Has at least one category tag (e.g. reputation)
- [x] Playbook has a tag for each vendor app used

# Other considerations (PR type specific)
- [x] If new playbook, there is a screenshot ending in .png with the same name as the playbook .json
- [x] Playbook major minor version matches repo (e.g. 5.5 != 6.0)
- [x] PR contains both .py and .json

---
Thanks for contributing!

### CODE REVIEW

**Review by P4T12ICK — COMMENTED** [review]
- append function in observable array need to be in the for loop
- use the following observable structure:
{
"type": "user",
"value": user_value,
"status": status_value,
"message": message_value"
}

**Comment by tccontre** [comment]
> * append function in observable array need to be in the for loop
> * use the following observable structure:
>   {
>   "type": "user",
>   "value": user_value,
>   "status": status_value,
>   "message": message_value"
>   }

fixed. thank you

**Review by P4T12ICK — CHANGES_REQUESTED** [review]
- In observable I don't think that credentials, request_id is needed

**Comment by tccontre** [comment]
> * In observable I don't think that credentials, request_id is needed

removed

**Comment by kelby-shelton** [comment]
1. Input name should be "user" with data type "user name" per our other playbooks that accept users like "Azure_AD_Graph_User_Attribute_Lookup"
2. Need to add data type "aws iam user name" to input data types. (Have to go to Administration > Administration Settings > CEF > +CEF > Enter any name for field and select data type "aws iam user name". Return to playbook and it will now be available as a selectable data type in the inputs).
4. Disable user action should use filtered datapath instead of regular playbook input datapath
5. "username observables" block should use filtered datapaths from "filter disable result" 
6. Change "AWS IAM Account" in observable output to "aws iam user name"
7. Add "aws_iam_user_name" to tags

After that, good to go!

**Comment by tccontre** [comment]
> 1. Input name should be "user" with data type "user name" per our other playbooks that accept users like "Azure_AD_Graph_User_Attribute_Lookup"
> 2. Need to add data type "aws iam user name" to input data types. (Have to go to Administration > Administration Settings > CEF > +CEF > Enter any name for field and select data type "aws iam user name". Return to playbook and it will now be available as a selectable data type in the inputs).
> 3. Disable user action should use filtered datapath instead of regular playbook input datapath
> 4. "username observables" block should use filtered datapaths from "filter disable result"
> 5. Change "AWS IAM Account" in observable output to "aws iam user name"
> 6. Add "aws_iam_user_name" to tags
> 
> After that, good to go!

Thanks Kelby. all suggestions are implemented and fixed.

**Review by P4T12ICK — APPROVED** [review]
Looks good to me

**Pull request merged**
