### PR TITLE
Add lower to evals

### PR DESCRIPTION
**Pull request by ljstella**
### Details

Add `lower()` wrapped around source fields in the beginning of BA detections due to BA case sensitivity. 

### Checklist

- [ ] Validate name matches `<platform>_<mitre att&ck technique>_<short description>` nomenclature
- [ ] [CI/CD](https://github.com/splunk/security_content/actions) jobs passed ✔️ 
- [ ] Validated SPL logic.
- [ ] Validated tags, description, and how to implement.
- [ ] Verified references match analytic.

### CODE REVIEW

**Comment by ljstella** [comment]
Couple of updates here: 

- Bhavin & I squirreled on this for a bit and found there were unpredictable detection failures when lower()'ing **all** the fields, so we are selectively lowering fields in the eval segment based upon their presence within the `query` variable. That involved some extra tinkering to ensure we were matching the specific ones we were using with a direct comparison.

- Pushed an updated `.vscode/launch.json` config to handle the contentctl.py convert command.

- Oddity discovered with `ssa_detections/endpoint/ssa___system_process_running_from_unexpected_location.yml`:
This detection appears to have been handwritten to take advantage of IN(...), which means we should **not** be mass-converting from Sigma -> BA SPL2.

**Comment by ljstella** [comment]
Full testing results: 
```
2023-10-05 16:31:29,436 INFO test_detection.py:600 - DTEST PASSED ssa___anomalous_usage_of_archive_tools.yml anomalies=6 decorated_events=16
2023-10-05 16:31:29,436 INFO test_detection.py:600 - DTEST PASSED ssa___attempt_to_delete_services.yml anomalies=4 decorated_events=7
2023-10-05 16:31:29,436 INFO test_detection.py:600 - DTEST PASSED ssa___attempt_to_disable_services.yml anomalies=3 decorated_events=3
2023-10-05 16:31:29,436 INFO test_detection.py:600 - DTEST PASSED ssa___attempted_credential_dump_from_registry_via_reg_exe.yml anomalies=4 decorated_events=236
2023-10-05 16:31:29,436 INFO test_detection.py:600 - DTEST PASSED ssa___bcdedit_failure_recovery_modification.yml anomalies=1 decorated_events=8
2023-10-05 16:31:29,436 INFO test_detection.py:600 - DTEST PASSED ssa___clear_unallocated_sector_using_cipher_app.yml anomalies=2 decorated_events=278
2023-10-05 16:31:29,436 INFO test_detection.py:600 - DTEST PASSED ssa___delete_a_net_user.yml anomalies=8 decorated_events=8
2023-10-05 16:31:29,437 INFO test_detection.py:600 - DTEST PASSED ssa___deleting_shadow_copies.yml anomalies=2 decorated_events=4
2023-10-05 16:31:29,437 INFO test_detection.py:600 - DTEST PASSED ssa___deny_permission_using_cacls_utility.yml anomalies=2 decorated_events=5
2023-10-05 16:31:29,437 INFO test_detection.py:600 - DTEST PASSED ssa___detect_prohibited_applications_spawning_cmd_exe.yml anomalies=3 decorated_events=3
2023-10-05 16:31:29,437 INFO test_detection.py:600 - DTEST PASSED ssa___detect_rclone_command_line_usage.yml anomalies=5 decorated_events=15
2023-10-05 16:31:29,437 INFO test_detection.py:600 - DTEST PASSED ssa___disable_net_user_account.yml anomalies=4 decorated_events=4
2023-10-05 16:31:29,437 INFO test_detection.py:600 - DTEST PASSED ssa___dns_exfiltration_using_nslookup_app.yml anomalies=1 decorated_events=5
2023-10-05 16:31:29,437 INFO test_detection.py:600 - DTEST PASSED ssa___fsutil_zeroing_file.yml anomalies=1 decorated_events=5
2023-10-05 16:31:29,437 INFO test_detection.py:600 - DTEST PASSED ssa___grant_permission_using_cacls_utility.yml anomalies=2 decorated_events=5
2023-10-05 16:31:29,437 INFO test_detection.py:600 - DTEST PASSED ssa___hiding_files_and_directories_with_attrib_exe.yml anomalies=10 decorated_events=10
2023-10-05 16:31:29,437 INFO test_detection.py:600 - DTEST PASSED ssa___modify_acls_permission_of_files_or_folders.yml anomalies=5 decorated_events=5
2023-10-05 16:31:29,437 INFO test_detection.py:600 - DTEST PASSED ssa___office_product_spawning_windows_script_host.yml anomalies=2 decorated_events=5
2023-10-05 16:31:29,437 INFO test_detection.py:600 - DTEST PASSED ssa___resize_shadowstorage_volume.yml anomalies=10 decorated_events=22
2023-10-05 16:31:29,437 INFO test_detection.py:600 - DTEST PASSED ssa___sdelete_application_execution.yml anomalies=1 decorated_events=271
2023-10-05 16:31:29,437 INFO test_detection.py:600 - DTEST PASSED ssa___services_lolbas_execution_process_spawn.yml anomalies=2 decorated_events=2
2023-10-05 16:31:29,437 INFO test_detection.py:600 - DTEST PASSED ssa___system_process_running_from_unexpected_location.yml anomalies=1 decorated_events=2
2023-10-05 16:31:29,438 INFO test_detection.py:600 - DTEST PASSED ssa___wbadmin_delete_system_backups.yml anomalies=2 decorated_events=8
2023-10-05 16:31:29,438 INFO test_detection.py:600 - DTEST PASSED ssa___wevtutil_usage_to_clear_logs.yml anomalies=3 decorated_events=3
2023-10-05 16:31:29,438 INFO test_detection.py:600 - DTEST PASSED ssa___wevtutil_usage_to_disable_logs.yml anomalies=2 decorated_events=2
2023-10-05 16:31:29,438 INFO test_detection.py:600 - DTEST PASSED ssa___windows_bits_job_persistence.yml anomalies=4 decorated_events=8
2023-10-05 16:31:29,438 INFO test_detection.py:600 - DTEST PASSED ssa___windows_bitsadmin_download_file.yml anomalies=1 decorated_events=8
2023-10-05 16:31:29,438 INFO test_detection.py:600 - DTEST PASSED ssa___windows_certutil_decode_file.yml anomalies=2 decorated_events=7
2023-10-05 16:31:29,438 INFO test_detection.py:600 - DTEST PASSED ssa___windows_certutil_urlcache_download.yml anomalies=3 decorated_events=60
2023-10-05 16:31:29,438 INFO test_detection.py:600 - DTEST PASSED ssa___windows_certutil_verifyctl_download.yml anomalies=1 decorated_events=60
2023-10-05 16:31:29,438 INFO test_detection.py:600 - DTEST PASSED ssa___windows_com_hijacking_inprocserver32_modification.yml anomalies=2 decorated_events=2
2023-10-05 16:31:29,438 INFO test_detection.py:600 - DTEST PASSED ssa___windows_curl_upload_to_remote_destination.yml anomalies=36 decorated_events=93
2023-10-05 16:31:29,438 INFO test_detection.py:600 - DTEST PASSED ssa___windows_default_group_policy_object_modified_with_gpme.yml anomalies=1 decorated_events=23
2023-10-05 16:31:29,438 INFO test_detection.py:600 - DTEST PASSED ssa___windows_defender_tools_in_non_standard_path.yml anomalies=2 decorated_events=3
2023-10-05 16:31:29,438 INFO test_detection.py:600 - DTEST PASSED ssa___windows_diskshadow_proxy_execution.yml anomalies=1 decorated_events=2
2023-10-05 16:31:29,438 INFO test_detection.py:600 - DTEST PASSED ssa___windows_dotnet_binary_in_non_standard_path.yml anomalies=2 decorated_events=3
2023-10-05 16:31:29,438 INFO test_detection.py:600 - DTEST PASSED ssa___windows_exchange_powershell_module_usage.yml anomalies=12 decorated_events=12
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_execute_arbitrary_commands_with_msdt.yml anomalies=3 decorated_events=4
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_file_share_discovery_with_powerview.yml anomalies=1 decorated_events=12
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_findstr_gpp_discovery.yml anomalies=1 decorated_events=15
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_ingress_tool_transfer_using_explorer.yml anomalies=1 decorated_events=8
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_lolbin_binary_in_non_standard_path.yml anomalies=1 decorated_events=3
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_mshta_child_process.yml anomalies=14 decorated_events=44
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_mshta_command_line_url.yml anomalies=3 decorated_events=44
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_mshta_inline_hta_execution.yml anomalies=7 decorated_events=44
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_odbcconf_load_response_file.yml anomalies=1 decorated_events=9
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_os_credential_dumping_with_ntdsutil_export_ntds.yml anomalies=8 decorated_events=8
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_os_credential_dumping_with_procdump.yml anomalies=6 decorated_events=10
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_powershell_connect_to_internet_with_hidden_window.yml anomalies=20 decorated_events=107
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_powershell_disabled_kerberos_pre_authentication_discovery_get_aduser.yml anomalies=1 decorated_events=12
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_powershell_disabled_kerberos_pre_authentication_discovery_with_powerview.yml anomalies=1 decorated_events=1
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_powershell_downloadfile.yml anomalies=1 decorated_events=1
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_powershell_start_bitstransfer.yml anomalies=2 decorated_events=14
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_powersploit_gpp_discovery.yml anomalies=1 decorated_events=2
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_rasautou_dll_execution.yml anomalies=5 decorated_events=8
2023-10-05 16:31:29,439 INFO test_detection.py:600 - DTEST PASSED ssa___windows_rename_system_utilities_acccheckconsole_exe_lolbas_in_non_standard_path.yml anomalies=1 decorated_events=160
2023-10-05 16:31:29,440 INFO test_detection.py:600 - DTEST PASSED ssa___windows_rename_system_utilities_adplus_exe_lolbas_in_non_standard_path.yml anomalies=1 decorated_events=160
2023-10-05 16:31:29,440 INFO test_detection.py:600 - DTEST PASSED ssa___windows_rename_system_utilities_advpack_dll_lolbas_in_non_standard_path.yml anomalies=1 decorated_events=160
2023-10-05 16:31:29,440 INFO test_detection.py:600 - DTEST PASSED ssa___windows_rename_system_utilities_agentexecutor_exe_lolbas_in_non_standard_path.yml anomalies=1 decorated_events=160
2023-10-05 16:31:29,440 INFO test_detection.py:600 - DTEST PASSED ssa___windows_rename_system_utilities_appinstaller_exe_lolbas_in_non_standard_path.yml anomalies=1 decorated_events=160
2023-10-05 16:31:29,440 INFO test_detection.py:600 - DTEST PASSED ssa___windows_rename_system_utilities_appvlp_exe_lolbas_in_non_standard_path.yml anomalies=1 decorated_events=160
2023-10-05 16:31:29,440 INFO test_detection.py:600 - DTEST PASSED ssa___windows_rename_system_utilities_aspnet_compiler_exe_lolbas_in_non_standard_path.yml anomalies=1 decorated_events=160
2023-10-05 16:31:29,440 INFO test_detection.py:600 - DTEST PASSED ssa___windows_rename_system_utilities_at_exe_lolbas_in_non_standard_path.yml anomalies=1 decorated_events=160
2023-10-05 16:31:29,440 INFO test_detection.py:600 - DTEST PASSED ssa___windows_rename_system_utilities_atbroker_exe_lolbas_in_non_standard_path.yml anomalies=1 decorated_events=160
2023-10-05 16:31:29,440 INFO test_detection.py:600 - DTEST PASSED ssa___windows_rundll32_comsvcs_memory_dump.yml anomalies=2 decorated_events=4
2023-10-05 16:31:29,440 INFO test_detection.py:600 - DTEST PASSED ssa___windows_rundll32_inline_hta_execution.yml anomalies=2 decorated_events=44
2023-10-05 16:31:29,440 INFO test_detection.py:600 - DTEST PASSED ssa___windows_script_host_spawn_msbuild.yml anomalies=4 decorated_events=5
2023-10-05 16:31:29,440 INFO test_detection.py:600 - DTEST PASSED ssa___windows_system_binary_proxy_execution_compiled_html_file_decompile.yml anomalies=3 decorated_events=5
2023-10-05 16:31:29,440 INFO test_detection.py:600 - DTEST PASSED ssa___windows_system_binary_proxy_execution_compiled_html_file_url_in_command_line.yml anomalies=1 decorated_events=22
2023-10-05 16:31:29,440 INFO test_detection.py:600 - DTEST PASSED ssa___windows_system_binary_proxy_execution_compiled_html_file_using_infotech_storage_handlers.yml anomalies=3 decorated_events=22
2023-10-05 16:31:29,440 INFO test_detection.py:600 - DTEST PASSED ssa___windows_system_binary_proxy_execution_msiexec_dllregisterserver.yml anomalies=1 decorated_events=33
2023-10-05 16:31:29,440 INFO test_detection.py:600 - DTEST PASSED ssa___windows_system_binary_proxy_execution_msiexec_remote_download.yml anomalies=1 decorated_events=33
2023-10-05 16:31:29,440 INFO test_detection.py:600 - DTEST PASSED ssa___windows_system_binary_proxy_execution_msiexec_unregister_dll.yml anomalies=1 decorated_events=33
2023-10-05 16:31:29,441 INFO test_detection.py:600 - DTEST PASSED ssa___windows_wmiprvse_spawn_msbuild.yml anomalies=1 decorated_events=5
2023-10-05 16:31:29,441 INFO test_detection.py:622 - overall status=SUCCESS detections=74 ok=74 failed=0 errors=0
````

**Comment by ljstella** [comment]
After speaking with Bhavin, updated the following two detections:
```
ssa___system_services_lolbas_execution_process_spawn.yml
ssa___windows_lolbin_binary_in_non_standard_path.yml
```

These now take advantage of using the `fieldname IN ("value1", "value2",..."valueN")` syntax. This is not currently able to be converted to from Sigma, so these two plus the previously mentioned one should not be converted.

Testing:
```
2023-10-06 15:54:04,397 INFO test_detection.py:600 - DTEST PASSED ssa___windows_lolbin_binary_in_non_standard_path.yml anomalies=1 decorated_events=3
2023-10-06 15:42:49,992 INFO test_detection.py:600 - DTEST PASSED ssa___services_lolbas_execution_process_spawn.yml anomalies=2 decorated_events=2
```

**Comment by patel-bhavin** [comment]
Looks good!

**Pull request merged**
