### PR TITLE
detection service: update to package  folder

### PR DESCRIPTION
**Pull request by patel-bhavin**
Update to detection testing service code to grab package from a new directory

### CODE REVIEW

**Comment by P4T12ICK** [comment]
We also need to add the parameter --product which you added into generate as required input.

**Comment by patel-bhavin** [comment]
@P4T12ICK 👍 done!! good eye there

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Malicious Powershell Executed As A Service :white_check_mark:
- diskUsage: 135168
- runDuration: 0.754s
- scanCount: 21

**Review by P4T12ICK — APPROVED** [review]
Good job @patel-bhavin

**Pull request merged**
