### PR TITLE
IcedHaagID

### PR DESCRIPTION
**Pull request by MHaggis**
## New Analytics
- Windows Curl Download to Suspicious Path (Passed)
- Windows Curl Upload to Remote Destination (Passed)
- WinEvent Windows Task Scheduler Event Action Started (Passed)

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows Curl Download to Suspicious Path :white_check_mark:
- diskUsage: 622592
- runDuration: 3.0260000000000002s
- scanCount: 185

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

WinEvent Windows Task Scheduler Event Action Started :x:
- diskUsage: 192512
- runDuration: 1.112s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

WinEvent Windows Task Scheduler Event Action Started :x:
- diskUsage: 151552
- runDuration: 1.367s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

WinEvent Windows Task Scheduler Event Action Started :x:
- diskUsage: 151552
- runDuration: 1.0210000000000001s
- scanCount: 0

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

WinEvent Windows Task Scheduler Event Action Started :x:
- diskUsage: 155648
- runDuration: 0.96s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

WinEvent Windows Task Scheduler Event Action Started :x:
- diskUsage: 155648
- runDuration: 0.926s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

WinEvent Windows Task Scheduler Event Action Started :x:
- diskUsage: 155648
- runDuration: 1.387s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

WinEvent Windows Task Scheduler Event Action Started :white_check_mark:
- diskUsage: 159744
- runDuration: 1.002s
- scanCount: 72

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows Curl Upload to Remote Destination :white_check_mark:
- diskUsage: 368640
- runDuration: 2.593s
- scanCount: 339

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
