### PR TITLE
Nterl0k - [T1649] - I am certify-able.

### PR DESCRIPTION
**Pull request by nterl0k**
### Details

Adds a number of detections for ADCS abuse, specifically ESC1 using common attacker tools Certify and the python derivative Certipy. 

Pending approval of https://github.com/splunk/attack_data/pull/809 

Added certify.exe and ceripy.exe, common compile names of these attacker tools, the attacker tool lookup.

https://github.com/GhostPack/Certify 
https://github.com/ly4k/Certipy

### Checklist

- [ ] Validate name matches `<platform>_<mitre att&ck technique>_<short description>` nomenclature
- [ ] [CI/CD](https://github.com/splunk/security_content/actions) jobs passed ✔️ 
- [ ] Validated SPL logic.
- [ ] Validated tags, description, and how to implement.
- [ ] Verified references match analytic.

### CODE REVIEW

**Comment by patel-bhavin** [comment]
Hello @nterl0k : thanks for a wholesome PR! i have added some comments on the attack_data PR, if you can take a look that will be great!

**Comment by patel-bhavin** [comment]
also, if you click on the "build-and-validate", you can see what are the basic failures in the PR for validation
image

https://github.com/splunk/security_content/actions/runs/5637044788/job/15269724322?pr=2777

That said, i recommend the following: in your repo: we setup the following and run the commands locally for validation
```pip install virtualenv
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
python contentctl.py -p . validate -pr ESCU

**NOTE**: I still will have to create duplicates for detection testing! Thank you for the patience and consistently helping the community with your contributions!

**Comment by nterl0k** [comment]
@patel-bhavin I split the detection log in https://github.com/splunk/attack_data/pull/809 as requested and updated the test files for these detections accordingly.

Let me know if anything else needs tweaking.

**Comment by patel-bhavin** [comment]
Hello @nterl0k : Thank you for splitting up the attack data, I created another PR to upload you attack data as git lfs instead of committing the file to the repo. After doing some fixing up and  testing on https://github.com/splunk/security_content/pull/2787 , we found a couple of issues and removed couple detections until they are validated and passes our detection testing

- Detect Certipy File Modifications : GUIDs dont match and hence the search is failing!

image

- we were unable to validate `windows_steal_authentication_certificates___esc1_abuse.yml`

We really appreciate your contribution to this repo and helping other blue teams!

**Comment by patel-bhavin** [comment]
The rest of the content is merged! Closing this PR! Thank you again :)

**Comment by nterl0k** [comment]
@patel-bhavin let me investigate those detections a bit more and I'll make a separate PR if needed 

The GUID issue should be easy to fix, probably a result of me splitting the detection data.

Can you tell me what couldn't be validated on windows_steal_authentication_certificates___esc1_abuse.yml ?

**Comment by nterl0k** [comment]
@patel-bhavin - I was able to spin up a fresh instance and get the logic in "windows_steal_authentication_certificates_esc1_abuse.yml" to work. 

What are you seeing on your side?

image

**Comment by nterl0k** [comment]
@patel-bhavin  I updated the test data for "Detect Certipy File Modification" via https://github.com/splunk/attack_data/pull/826

**Pull request closed without merging**
