### PR TITLE
iceid_ttps

### PR DESCRIPTION
**Pull request by tccontre**
## IceID Defense Evasion, Schedule task disabling, cmd execution TTPs

-  disable_defender_blockatfirstseen_feature.yml (passed)
-  disable_defender_enhanced_notification.yml (passed)
-  disable_defender_spynet_reporting.yml (passed)
-  disable_defender_submit_samples_consent_feature.yml (passed)
- disable_schedule_task.yml (passed)
- disable_defender_antivirus_registry.yml (passed)
- disable_defender_mpengine_registry.yml (passed)
-  disabling_defender_services.yml (passed)
 - wmic_noninteractive_app_uninstallation.yml (passed)
 - cmd_carry_out_string_command_parameter.yml (passed)

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Disable Schedule Task :white_check_mark:
- diskUsage: 598016
- runDuration: 6.205s
- scanCount: 7984

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Disable Defender Submit Samples Consent Feature :x:
- diskUsage: 491520
- runDuration: 2.579s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Disable Defender Submit Samples Consent Feature :white_check_mark:
- diskUsage: 524288
- runDuration: 1.989s
- scanCount: 45

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Disable Defender Spynet Reporting :white_check_mark:
- diskUsage: 512000
- runDuration: 2.593s
- scanCount: 45

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Disable Defender MpEngine Registry :white_check_mark:
- diskUsage: 516096
- runDuration: 3.17s
- scanCount: 45

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Disable Defender Enhanced Notification :white_check_mark:
- diskUsage: 516096
- runDuration: 2.354s
- scanCount: 45

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Disable Defender BlockAtFirstSeen Feature :white_check_mark:
- diskUsage: 503808
- runDuration: 1.7750000000000001s
- scanCount: 45

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Disable Defender AntiVirus Registry :white_check_mark:
- diskUsage: 516096
- runDuration: 1.836s
- scanCount: 46

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Wmic NonInteractive App Uninstallation :white_check_mark:
- diskUsage: 622592
- runDuration: 5.066s
- scanCount: 5238

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Disabling Defender Services :white_check_mark:
- diskUsage: 552960
- runDuration: 1.723s
- scanCount: 100

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

CMD Carry Out String Command Parameter :white_check_mark:
- diskUsage: 512000
- runDuration: 3.725s
- scanCount: 2113

**Review by mvelazc0 — APPROVED** [review]

**Pull request merged**
