### PR TITLE
AD_Discovery_TR-789_8

### PR DESCRIPTION
**Pull request by mvelazc0**
### New T1049 detections

* GetNetTcpconnection with PowerShell
* GetNetTcpconnection with PowerShell Script Block
* Network Connection Discovery With Arp
* Network Connection Discovery With Net
* Network Connection Discovery With Netstat

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetNetTcpconnection with PowerShell :white_check_mark:
- diskUsage: 585728
- runDuration: 2.399s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetNetTcpconnection with PowerShell Script Block :white_check_mark:
- diskUsage: 155648
- runDuration: 1.851s
- scanCount: 45

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Network Connection Discovery With Arp :white_check_mark:
- diskUsage: 491520
- runDuration: 3.344s
- scanCount: 2733

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Network Connection Discovery With Netstat :white_check_mark:
- diskUsage: 589824
- runDuration: 3.789s
- scanCount: 2996

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Network Connection Discovery With Arp :white_check_mark:
- diskUsage: 585728
- runDuration: 4.022s
- scanCount: 3066

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
