### PR TITLE
WIP - rel2 02-2020

### PR DESCRIPTION
**Pull request by MHaggis**
Analytic Story
- Suspicious Compiled HTML Activity
- Suspicious Regsvcs Regasm Activity
- Cobalt Strike

Analytics
- Detect HTML Help URL in Command Line (Passed)
- Detect HTML Help Spawn Child Process (Passed)
- Detect HTML Help Renamed (Passed)
- Detect HTML Help Using InfoTech Storage Handlers (Passed)
- Detect Regasm Spawning a Child Process (Passed)
- Detect Regsvcs Spawning a Child Process (Passed)
- Detect Regsvcs With Network Connection (Passed)
- Detect Regasm with no Command Line Arguments (Passed)
- Detect Regasm With Network Connection (Passed)
- Detect regsvcs with no Command Line Arguments (Passed)

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect HTML Help Spawn Child Process :white_check_mark:
- diskUsage: 397312
- runDuration: 5.418s
- scanCount: 6602

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect HTML Help URL in Command Line :white_check_mark:
- diskUsage: 397312
- runDuration: 5.405s
- scanCount: 6602

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect HTML Help Using Infotech Storage Handlers :white_check_mark:
- diskUsage: 401408
- runDuration: 5.71s
- scanCount: 6602

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect HTML Help Renamed :white_check_mark:
- diskUsage: 143360
- runDuration: 0.924s
- scanCount: 308

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Regasm Spawning a Process :white_check_mark:
- diskUsage: 405504
- runDuration: 2.875s
- scanCount: 2579

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Regasm Spawning a Process :white_check_mark:
- diskUsage: 405504
- runDuration: 2.922s
- scanCount: 2579

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Regsvcs Regasm Spawning a Process :white_check_mark:
- diskUsage: 405504
- runDuration: 2.891s
- scanCount: 2579

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Regsvcs With Network Connection :white_check_mark:
- diskUsage: 323584
- runDuration: 1.867s
- scanCount: 1620

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Regasm With Network Connection :white_check_mark:
- diskUsage: 323584
- runDuration: 1.8760000000000001s
- scanCount: 1620

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect Regasm with no Command Line Arguments :white_check_mark:
- diskUsage: 286720
- runDuration: 3.262s
- scanCount: 4205

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Detect regsvcs with no Command Line Arguments :white_check_mark:
- diskUsage: 286720
- runDuration: 3.2640000000000002s
- scanCount: 4205

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
