### PR TITLE
updating base on suggestions from mschilt in issue 1528

### PR DESCRIPTION
**Pull request by josehelps**
adjustments to the actual spl.

### CODE REVIEW

**Review by tccontre — DISMISSED** [review]

**Comment by patel-bhavin** [comment]
https://github.com/splunk/security_content/pull/1642/checks?check_run_id=3548532734

**Review by patel-bhavin — DISMISSED** [review]

**Comment by patel-bhavin** [comment]
https://github.com/splunk/security_content/runs/3549147312?check_suite_focus=true

**Comment by patel-bhavin** [comment]
wil run batch for this

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Registry Keys Used For Persistence :x:
- diskUsage: 131072
- runDuration: 0.003s
- scanCount: 0

**Comment by patel-bhavin** [comment]
updated the search logic

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Registry Keys Used For Persistence :white_check_mark:
- diskUsage: 708608
- runDuration: 5.321s
- scanCount: 6031

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
