### PR TITLE
linux_persist_priv_batch_4

### PR DESCRIPTION
**Pull request by tccontre**
### Linux Persistence And Privilege Escalation Detections

- linux_add_user_account.yml (passed)
- linux_common_process_for_elevation_control.yml (passed)
- linux_doas_conf_file_creation.yml(passed)
- linux_doas_tool_execution.yml(passed)
- linux_possible_access_to_credential_files.yml(passed)
- linux_possible_access_to_sudoers_file.yml (passed)
- linux_sudo_or_su_execution.yml(passed)

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Add User Account :white_check_mark:
- diskUsage: 516096
- runDuration: 2.422s
- scanCount: 1412

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Doas Conf File Creation :white_check_mark:
- diskUsage: 479232
- runDuration: 5.507s
- scanCount: 7226

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Doas Tool Execution :white_check_mark:
- diskUsage: 507904
- runDuration: 10.58s
- scanCount: 14622

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Possible Access To Credential Files :white_check_mark:
- diskUsage: 385024
- runDuration: 3.031s
- scanCount: 1160

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Sudo OR Su Execution :white_check_mark:
- diskUsage: 409600
- runDuration: 3.513s
- scanCount: 3388

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Possible Access To Sudoers File :white_check_mark:
- diskUsage: 364544
- runDuration: 4.37s
- scanCount: 1165

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Common Process For Elevation Control :white_check_mark:
- diskUsage: 516096
- runDuration: 3.745s
- scanCount: 3617

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
