### PR TITLE
Hpot ttp

### PR DESCRIPTION
**Pull request by tccontre**
## Detection Found In Honeypot Loading Mimikatz and xmrig

1. Powershell Creating Thread Mutex (passed)
2. Powershell Processing Stream Of Data (passed)
3. Powershell Using memory As Backing Store (passed)
4. Recon AVProduct Through Pwh or WMI (passed)
5. Recon Using  WMI Class (passed)
6. WMI Recon Running Process Or Services (passed)

### CODE REVIEW

**Comment by tccontre** [comment]
redundant

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Powershell Creating Thread Mutex :white_check_mark:
- diskUsage: 188416
- runDuration: 1.201s
- scanCount: 131

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Powershell Processing Stream Of Data :white_check_mark:
- diskUsage: 188416
- runDuration: 0.926s
- scanCount: 130

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Powershell Using memory As Backing Store :white_check_mark:
- diskUsage: 188416
- runDuration: 0.804s
- scanCount: 130

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Recon AVProduct Through Pwh or WMI :white_check_mark:
- diskUsage: 188416
- runDuration: 1.164s
- scanCount: 130

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Recon Using  WMI Class :white_check_mark:
- diskUsage: 192512
- runDuration: 1.284s
- scanCount: 131

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

WMI Recon Running Process Or Services :white_check_mark:
- diskUsage: 188416
- runDuration: 0.8290000000000001s
- scanCount: 130

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Powershell Creating Thread Mutex :white_check_mark:
- diskUsage: 163840
- runDuration: 0.778s
- scanCount: 130

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Powershell Processing Stream Of Data :white_check_mark:
- diskUsage: 172032
- runDuration: 0.8140000000000001s
- scanCount: 131

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Powershell Using memory As Backing Store :white_check_mark:
- diskUsage: 163840
- runDuration: 0.9500000000000001s
- scanCount: 6

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Recon AVProduct Through Pwh or WMI :white_check_mark:
- diskUsage: 167936
- runDuration: 0.9380000000000001s
- scanCount: 130

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Recon Using  WMI Class :white_check_mark:
- diskUsage: 172032
- runDuration: 0.858s
- scanCount: 130

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

WMI Recon Running Process Or Services :white_check_mark:
- diskUsage: 167936
- runDuration: 1.2730000000000001s
- scanCount: 130

**Review by P4T12ICK — APPROVED** [review]
looks good to me

**Pull request merged**
