### PR TITLE
renamed ssa detections

### PR DESCRIPTION
**Pull request by ghoto**
Renamed detections to follow pattern ssa___DETECTION.yml

### CODE REVIEW

**Comment by patel-bhavin** [comment]
Hey @ghoto : Instead of renaming files, do you think we can add "SSA" to one of the newly added fields in the detection.yml similar to this PR : https://github.com/splunk/security_content/pull/1119/files#diff-adb9c54981217b8fda58c2be8bf6072bd3df503ae2f4f7347abdebcab7cd4597R44

**Comment by trogdorsey** [comment]
We don't really have a product name, so I wouldn't include one for these yet.

**Comment by ghoto** [comment]
@patel-bhavin I can add one when we have a name. Anyways, I don't understand why these tests are failing. Also, @d1vious is this what you wanted?

**Review by josehelps — APPROVED** [review]

**Comment by josehelps** [comment]
yep thank you @ghoto merged in!

**Pull request merged**
