### PR TITLE
AD_Discovery_TR-789_7

### PR DESCRIPTION
**Pull request by mvelazc0**
## New T1018 Detections
* Domain Controller Discovery with Nltest
* Domain Controller Discovery with Wmic
* Remote System Discovery with Dsquery
* Remote System Discovery with Net
* Remote System Discovery with Wmic
* GetAdComputer with PowerShell Script Block
* GetWmiObject Ds Computer with PowerShell Script Block
* Remote System Discovery with Adsisearcher
* GetDomainComputer with PowerShell Script Block
* GetDomainController with PowerShell Script Block
* GetAdComputer with PowerShell
* GetDomainComputer with PowerShell
* GetDomainController with PowerShell
* GetWmiObject Ds Computer with PowerShell

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetDomainComputer with PowerShell Script Block :white_check_mark:
- diskUsage: 155648
- runDuration: 1.081s
- scanCount: 39

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Domain Controller Discovery with Nltest :white_check_mark:
- diskUsage: 585728
- runDuration: 1.854s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Domain Controller Discovery with Wmic :white_check_mark:
- diskUsage: 491520
- runDuration: 3.35s
- scanCount: 2859

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetAdComputer with PowerShell :white_check_mark:
- diskUsage: 581632
- runDuration: 1.991s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetAdComputer with PowerShell Script Block :white_check_mark:
- diskUsage: 155648
- runDuration: 1.0230000000000001s
- scanCount: 2

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetDomainComputer with PowerShell :white_check_mark:
- diskUsage: 585728
- runDuration: 2.218s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetDomainController with PowerShell :white_check_mark:
- diskUsage: 585728
- runDuration: 2.455s
- scanCount: 4

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetDomainController with PowerShell Script Block :white_check_mark:
- diskUsage: 155648
- runDuration: 1.0170000000000001s
- scanCount: 70

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetWmiObject Ds Computer with PowerShell :white_check_mark:
- diskUsage: 376832
- runDuration: 2.08s
- scanCount: 3

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

GetWmiObject Ds Computer with PowerShell Script Block :white_check_mark:
- diskUsage: 163840
- runDuration: 1.37s
- scanCount: 9

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Remote System Discovery with Adsisearcher :white_check_mark:
- diskUsage: 159744
- runDuration: 1.494s
- scanCount: 1

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Remote System Discovery with Dsquery :white_check_mark:
- diskUsage: 487424
- runDuration: 3.4050000000000002s
- scanCount: 2859

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Remote System Discovery with Net :white_check_mark:
- diskUsage: 602112
- runDuration: 2.145s
- scanCount: 8

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Remote System Discovery with Dsquery :white_check_mark:
- diskUsage: 487424
- runDuration: 3.4370000000000003s
- scanCount: 2859

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Remote System Discovery with Wmic :white_check_mark:
- diskUsage: 376832
- runDuration: 2.4250000000000003s
- scanCount: 4

**Review by MHaggis — APPROVED** [review]

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
