### PR TITLE
linux_persist_priv_batch_5

### PR DESCRIPTION
**Pull request by tccontre**
### Linux Persistence And Privilege Escalation Detections

- linux_nopasswd_entry_in_sudoers_file.yml (passed)
- linux_possible_append_command_to_profile_config_file.yml
- linux_possible_access_or_modification_of_sshd_config_file.yml (passed)
- tests/endpoint/linux_possible_access_or_modification_of_sshd_config_file.test.yml (passed)

### Docker Testing (All detection passed - success.csv)
Screenshot 2022-01-12 at 09 57 39

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Possible Ssh Key File Creation :white_check_mark:
- diskUsage: 466944
- runDuration: 9.398s
- scanCount: 14309

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Possible Access Or Modification Of sshd_config File :white_check_mark:
- diskUsage: 372736
- runDuration: 4.072s
- scanCount: 3968

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux Possible Append Command To Profile Config File :x:
- diskUsage: 397312
- runDuration: 14.344s
- scanCount: 25932

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Linux NOPASSWD Entry In Sudoers File :white_check_mark:
- diskUsage: 421888
- runDuration: 18.436s
- scanCount: 33475

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
